#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "æﬁ–Õ»Æ",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¡ı¿œ≈©",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ƒ¡—Ú≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ƒ¡—Ú±ﬁ",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "—Ú√´»π",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ª®¥Ûπ√",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "≤®Àπ≈´",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Õ‰µ∂",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¥Û∫Ï≤º≈€",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ª§…Ω π’ﬂ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ã“ƒæΩ£",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¥Û∫∫",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                " ˜÷¶",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Œ‰¡÷¥Û∫¿Ω‹",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Ã˙ª§Œ¿",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Õ≠ª§Œ¿",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Ô⁄ ¶",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                " ØÀ¯",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "–°—æª∑",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":               HIG"«≥¬Ã–°π”"NOR,
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "π˘·‘—Ù",
                "quest_type":           "…±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "∫˛…œ≤›",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "≤›…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œª®",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ª®…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¡÷œ…∂˘",
                "quest_type":           "…±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "∫˛…œæ∆",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "æ∆…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œ¡¯",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¡¯…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫Ï≥ÒŒË∆˜",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œ≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "≈Æ…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œÀÆ",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀÆ…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œ—©",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "—©…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∫˛…œ‘¬",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "‘¬…¿",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¥‰”Ò≈˝≈√",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ªÙ”¢",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∂≈“˜",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "æ¢◊∞…ŸƒÍ",
                "quest_type":           "…±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "«‡“¬…Ÿ≈Æ",
                "quest_type":           "…±",
                "time":                 840,
                "exp_bonus":            55,
        ]),
        ([      "quest":                "«‡¥¯",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "«‡“¬",
                "quest_type":           "—∞",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "”ŒøÕ",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ª∆…Ω∑Áæ∞Õº",
                "quest_type":           "—∞",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "∞¢∏£",
                "quest_type":           "…±",
                "time":                 840,
                "exp_bonus":            55,
        ]),
        ([      "quest":                "¥Û∫˙◊”",
                "quest_type":           "…±",
                "exp_bonus":            45,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}        
