#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "´¿½ðÒ¶×Ó",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÑÎ°Í",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÐÂ½®µØÌº",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¿¨ÄãÍßÒÀÒÂ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "°¬ÌáÀ­Ë¹È¹",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ó¢¼ªÉ³Ð¡µ¶",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "×°ÂíÄÌ×ÓµÄÆ¤´ü",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
/*        ([      "quest":              HIC"ÌìÉ½Ñ©Á«"NOR,
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),*/
        ([      "quest":                "ÆáºÚµÄµ¶",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "âÎ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ºÚÉ´ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¿¾°ü×Ó",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "×¥·¹",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¿¾ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "µÎÑªµ¶",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÌúÊÖÕÆ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            30,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}  
