#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ÛÔ∑…”Í",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "÷Ï»∏’Ω“¬",
                "quest_type":           "—∞",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ª®∑…",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                " •¡È≈˚∑Á",
                "quest_type":           "—∞",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÛÔ¬¸∑Á",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "–˛Œ‰’Ω≈€",
                "quest_type":           "—∞",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "µ¿ ø",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "À’∫Ï∂˘",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "–°ÕØ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":               HIY"«≥ª∆–°π”"NOR,
                "quest_type":           "—∞",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ΩÕØ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "≥˛≥˛",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "∂¡«ß¿Ô",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Õı∑Á",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "…Ã”Ò¡˙",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏ¡˙",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏ∑Ô",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏŒﬁµ∂",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏŒﬁΩ£",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏª¢",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏ–˚",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏ∑ ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÃÏ ﬁ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "∂®∞Ó¥Û ¶",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "‘∆¡˜",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "–ÏƒÔ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "∂Òƒß",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "√Ó¡‰…Ÿ≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "≤ı“Ì…¥“¬",
                "quest_type":           "—∞",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "≈„æ∆≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            60,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}  
