#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "³ø×Ó",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "±ÌÓñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "»¤ËÂ²ØÄá",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Òõ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ò»»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "time":                 360,
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´óºìÄáÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ð¡´ä",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "·ÛºìÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ï¸Ã·½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "µÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ð»³¤ÇÚ",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ËÎ³¤Çå",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "½ð»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´ó³ø",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Â±Î¶¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÑÅ¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ß¡ÉÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÇÎð±Ä¸",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Îèµû²ÊÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ð¡Ã¨ßä",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ð¡°×ÍÃ",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Öª¿ÍµÀÈË",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "»ÆÉ«µÀ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Çà²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÍõÓ¨",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÑàÉº",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "°×ÓñÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "½õ²á",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ë®Áé¹â",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ºûµû",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÍÂÂ³·¬ÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "¿Õ´â",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÌúÕÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÃÞ²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "±®ÎÄÍØ±¾",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "½­ºþÖÐÈË",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÂíÃæ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Å£Í·",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÌúË÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "¼Ïîí",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "É³ÂÞÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),  
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}      
