#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÀÏÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Ð¡µ£··",
                "quest_type":           "É±",
                "exp_bonus":            2, 
        ]),
        ([      "quest":                "Ð¡··",
                "quest_type":           "É±",
                "exp_bonus":            2, 
        ]),
        ([      "quest":                "Æ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Öñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,   
        ]),
        ([      "quest":                "Ð¡¶þ¸ç",
               "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÁúÐ¡ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÂòÂòÌá",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Î¬Îá¶û»¨Ã±",
                "quest_type":           "Ñ°",
                 "exp_bonus":           2,
        ]),
        ([      "quest":                "ÎÞºË°×ÆÏÌÑ",
                "quest_type":           "Ñ°",
                 "exp_bonus":           2,
        ]),
        ([      "quest":                "°¢ÒÀ¹ÅÀö",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "°¬ÌáÀ­Ë¹È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]), 
// end 2k 
        ([      "quest":                "»¤ÐÄ¾µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Ò°Ñ¼",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "À×»ðÖé",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
       ]),
        ([      "quest":                "ÏÊÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Ä¥²Ëµ¶µÄ",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "´©¿ªñÉ¿ãµÄÐ¡º¢¶ù",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÂôÓãµÄ",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÂòÓãµÄÐ¡¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Å©¼ÒÅ®",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "¼¦Ã«ë¦×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Å©¾ßµêÀÏ°å",
                "quest_type":           "É±",
               "exp_bonus":            3,
        ]),
        ([      "quest":                "Ç§½ðÐ¡½ã",
                "quest_type":           "É±",
                "exp_bonus":            3,   
        ]),
        ([      "quest":                "Òøô¢",
                "quest_type":           "Ñ°",  
                "exp_bonus":            3,     
        ]),
        ([      "quest":                "ÇáÂÞ³ñÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,   
        ]),
//end 3k 
        ([      "quest":                "Öñ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Çå²¨¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÆÆ¾É²»¿°µÄ³¤ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Ô¬¼§",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "°×³ñ³¤Åû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÍõÊ¯½³",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
       ([      "quest":                "ÑîÀÏÌ«",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",  
                "exp_bonus":            4,     
        ]),
        ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",  
                "exp_bonus":            4,     
        ]),
        ([      "quest":                "Ð¡³´·ÛË¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÂäµÚÊéÉú",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "×¥ÆÆÃÀÈËÁ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]), 
//end 4k
        ([      "quest":                "¡¸²ðÕÐÃØ¾ö¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¡¸ÉÁ¶ãÖ®Êõ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¡¸È­·¨ÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "ÍÁ·Ë",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Æ¤ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¹Â»êÒ°¹í",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Óã",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¿¾ÓãÈâ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¹È»Û¶ù",
                "quest_type":           "É±",  
                "exp_bonus":            5,
        ]),
        ([      "quest":                "³ÇÚòÓ¡",
                "quest_type":           "Ñ°",  
                "exp_bonus":            5,
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",  
                "exp_bonus":            5,   
        ]),
        ([      "quest":                "µÇÍ½×Ó",
                "quest_type":           "É±",
                "exp_bonus":            5,   
        ]),
        ([      "quest":                "ÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
//end 5k
        ([      "quest":                "ÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "ÑÌ¶·",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "³ÁÏãÕòµÄµØÍ·Éß",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "ºìÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,   
        ]),
        ([      "quest":                "ÂÌÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,   
        ]),
        ([      "quest":                "Äî¾­µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            6,   
        ]),
        ([      "quest":                "»Ò²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,   
        ]),
        ([      "quest":                "âã»ÚÍ½",
                "quest_type":           "É±",
                "exp_bonus":            6,   
        ]),
        ([      "quest":                "ÑÅ·¼",
                "quest_type":           "É±",  
                "exp_bonus":            6,     
        ]),
        ([      "quest":                "Íõ»¢",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Áø·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Ïã¿Í",
                "quest_type":           "É±",  
                "exp_bonus":            6,     
        ]), 
//end 6k
        ([      "quest":                "Ñà¶ù",
                "quest_type":           "É±",  
                "exp_bonus":            7,     
        ]),
        ([      "quest":                "²Ý±àÂìòÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "Ð¡±¦¶ù",
                "quest_type":           "É±",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "Öñ·òÈË",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "ÌôÉ½·ò",
                "quest_type":           "É±",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "´ÖÄ¾±âµ£",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",  
                "exp_bonus":            7,     
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "ÄêÇàÈË",
                "quest_type":           "É±",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "ÇàÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "Áù½Ç´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
//end 7k 
        ([      "quest":                "É¥¾¡ÌìÁ¼µÄÐóÉú",
                "quest_type":           "É±",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "µÇÉ½Õß",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "Ê¯»ÒÊ¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "¹È×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "òÐòÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "ÂìÒÏ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "ÍÂÂ³·¬ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            8, 
        ]),
        ([      "quest":                "ÎÚÀ­²´ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            8, 
        ]),
        ([      "quest":                "Ó¢¼ªÉ³Ð¡µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "âÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]), 
//end 8k 
        ([      "quest":                "ÁøÈôËÉ",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "´óÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "ÃÎ»À",  
                "quest_type":           "É±",  
                "exp_bonus":            9,   
                "difficulty":           15,
        ]),
        ([      "quest":                "·ç¾²",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "²É»¨æ¤",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "À¶ÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "ÆßÐÇ´¸",
                "quest_type":           "Ñ°",  
                "exp_bonus":            9,
        ]),
//end 9k
        ([      "quest":                "Ë®ÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¨½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
       ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "²ÊÈ¹",
                "quest_type":           "Ñ°",

                "exp_bonus":            10,   
        ]),
        ([      "quest":                "²ÉÁâÅ®",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ö£¼×",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¨¹Ã",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¼ÖÔ±Íâ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Á«¶ù",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÃåÓñ»¡",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]), 
//end 10k 
        ([      "quest":                "ÀÏÎÝÈË",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "¹Ø¶«´óºº",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Ñª³¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
       ([      "quest":                "¹Â»ê",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
//end 11k 
        ([      "quest":                "Õ½»ê",
                "quest_type":           "É±",
                "exp_bonus":            12,
        ]),     
        ([      "quest":                "ÎäÁÖÐ¡ºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            12,  
        ]),
        ([      "quest":                "Ãçµ¶",
                "quest_type":           "Ñ°",  
                "exp_bonus":            12,    
        ]),
        ([      "quest":                "¼«ÀÖåÐÒ£É¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "»¯Ê¬·Û",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "Ò¹ÐÐÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "¾«¸Ö·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "ºì×ìÐ¡ÂéÈ¸",
                "quest_type":           "É±",
                "exp_bonus":            12,
        ]), 
//end 12k 
        ([      "quest":                "ÔÆÓÎÉ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "ÃÞ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Ó­¿ÍÉ®",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "×ÏÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "°ËÀãÐþÌú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "ÂÌ¶¹Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Íã¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),  
//end 13k 
        ([      "quest":                "ÐíÁ®Áú",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "Åí³¤¾»",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ËÎ³¤Çå",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ÈËÓ°",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "Çà·æ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "öùÓã",
                "quest_type":           "É±",
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "Ë®Éß",
                "quest_type":           "É±",
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "ÈËÓ°",
                "quest_type":           "É±",  
                "exp_bonus":            15,  
        ]), 
//end 15k 
        ([      "quest":                "´ó³ø",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Â±Î¶¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ÑÅ¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ß¡ÉÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ÇÎð±Ä¸",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Îèµû²ÊÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]), 
//end 16k
                        
        ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",    
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ð¡´ä",
                "quest_type":           "É±",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",  
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "·ÛºìÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ï¸Ã·½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÄÁÑòÅ®",
                "quest_type":           "É±",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÑòÃ«È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
//end 18k 
        ([      "quest":                "³ø×Ó",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "±ÌÓñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»¤ËÂ²ØÄá",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Òõ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ò»»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "´óºìÄáÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
//end 20k
 
       ([      "quest":                "½ð»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            21,  
        ]),
        ([      "quest":                "É³ÂÞÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            21,
        ]),
        ([      "quest":                "Ð¡°×ÍÃ",
                "quest_type":           "É±",
                "exp_bonus":            23,  
        ]),
        ([      "quest":                "°×ÓñÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "½õ²á",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "Ë®Áé¹â",
                "quest_type":           "É±",
                "exp_bonus":            23,
                "difficulty":           15,
        ]),
        ([      "quest":                "ºûµû",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "ÍÂÂ³·¬ÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),

//end 23k 
        ([      "quest":                "ÂíÃæ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Å£Í·",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÌúË÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¼Ïîí",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "·çÉ§ÑÅÈË",
                "quest_type":           "É±",
                "exp_bonus":            27,
        ]),
        ([      "quest":                "Â½Îå´¨",
                "quest_type":           "É±",
                "exp_bonus":            27,
        ]),
        ([      "quest":                "ºÚÉ«×¯·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            27,
        ]),
        ([      "quest":                "·çóÝ",
                "quest_type":           "Ñ°",
                "exp_bonus":            27,
        ]),
//end 27k 
        ([      "quest":                "¿Õ¹â",
                "quest_type":           "É±",
                "exp_bonus":            29,
                "difficulty":           15,
        ]),
        ([      "quest":                "·¹²§",
                "quest_type":           "Ñ°",
                "exp_bonus":            29,
        ]),
        ([      "quest":                "ÌúÕÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            29,
        ]),
        ([      "quest":                "±®ÎÄÍØ±¾",
                "quest_type":           "Ñ°",
                "exp_bonus":            29,
        ]),
        ([      "quest":                "½­ºþÖÐÈË",
                "quest_type":           "É±",
                "exp_bonus":            29,
        ]),
//end 28k 
        ([      "quest":                "µÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ÍõÓ¨",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ÑàÉº",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]), 
//end 31k         
        ([      "quest":                "ºþÉÏ²Ý",
                "quest_type":           "É±",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "²ÝÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "ºþÉÏ»¨",
                "quest_type":           "É±",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "»¨ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            33,
        ]),
        ([      "quest":                "ºþÉÏ¾Æ",
                "quest_type":           "É±",
                "exp_bonus":            33,
        ]),
        ([      "quest":                "¾ÆÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            33,
        ]),
//end 33k 
        ([      "quest":                "Ô°¹¤¼ô",
                "quest_type":           "Ñ°",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "Ð¡Ô°¹¤",
                "quest_type":           "É±",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "Å®Ó¶ÈË",
                "quest_type":           "É±",
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "¼¦Ã«",
                "quest_type":           "Ñ°",  
                "exp_bonus":            34,   
        ]), 
//end 34k 
        ([      "quest":                "Óü×ä",
                "quest_type":           "É±",

                "exp_bonus":            37,
        ]),
        ([      "quest":                "¶Û½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "»¤Ôº",
                "quest_type":           "É±",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "Ð¡¶Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),
       ([      "quest":                "³ø×Ó",
                "quest_type":           "É±",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "±ÌÓñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]), 
//end 37k 
        ([      "quest":                "»¤ËÂÀ®Âï",
                "quest_type":           "É±",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "´óºìÉ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Ñô¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "³ÇÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            41,
        ]),

        ([      "quest":                "ËþÉ®",
                "quest_type":           "É±",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Èý»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
//end 41k 
        ([      "quest":                "¿¼Éú",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "·çÔÆÂí¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "ÀËÓÎÊ«ÈË",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "Ñ©ÌãëÙÖ¬Âí",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "Å£Æ¤Âí°°",
                "quest_type":           "Ñ°",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "ÎÄÈËÄ«¿Í",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "·çÁè",
                "quest_type":           "É±",

                "exp_bonus":            46,
                "difficulty":           20,
        ]),
//end 46k  
        ([      "quest":                "µ¥ÉíÌË×ÓÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "»õÆ±",
                "quest_type":           "Ñ°",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ÊÝæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ÅÖæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "·®·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            51,
                "difficulty":           20,
        ]), 
//end 51k  
        ([      "quest":                "Òø»¤ÎÀ",
                "quest_type":           "É±",  
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ºÚÉ«½Ì·þ",

                "quest_type":           "Ñ°",  
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ÍõÈô¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ÕÅËÆ¸Ö",
                "quest_type":           "É±", 
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ÀîÈü¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ÕÔÈç¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "»ÆÉ«½Ì·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,  
        ]), 
//end 55k 
        ([      "quest":                "Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "³¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "»ÆÒÂÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "½ðÇ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,

        ]),
        ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ºÚ¹·",
                "quest_type":           "É±",
                "exp_bonus":            60,
                "difficulty":           25,
        ]),
        ([      "quest":                "Í­Ç®ïÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]), 
//end 60k 
        ([      "quest":                "¹ùáÔÑô",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            65,
                "difficulty":           15,
        ]),
        ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ÏìÎ²Éß",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "´óºº",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "Ê÷Ö¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,

        ]),
//end 65k 
        ([      "quest":                "ºþÉÏÅ®",
                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Å®ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "ºþÉÏË®",
                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Ë®ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "ºþÉÏÑ©",
                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Ñ©ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
//end 71k 
        ([      "quest":                "ÀîÕÆ¹ñ",
                "quest_type":           "É±",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "ÀÏºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "°×ÃÞôÂôÄ",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),

        ([      "quest":                "Ï¹ÀÏµù",
                "quest_type":           "É±",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "¶þºúÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
//end 78k 
        ([      "quest":                "Ð»³¤ÇÚ",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           20,
        ]),
        ([      "quest":                "Àî³¤É÷",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           20,
        ]),
        ([      "quest":                "¹©Ïã",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ì«¼«È­Á·¹¦Í¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]), 
//end 85k 
        ([      "quest":                "ÎäÁÖ´óºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            89,

        ]),
        ([      "quest":                "Ìú»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "Í­»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
//end 89k 
        ([      "quest":                "ºÚ¹Ú¾Þòþ",
                "quest_type":           "É±",
                "exp_bonus":            93,
                "difficulty":           15,
        ]),
        ([      "quest":                "Öª¿ÍµÀÈË",
                "quest_type":           "É±",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "»ÆÉ«µÀ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "Çà²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
// end 93k 
        ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "exp_bonus":            101,
        ]),
        ([      "quest":                "Íäµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            101,
        ]),
        ([      "quest":                "´óºì²¼ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            101,

        ]),
        ([      "quest":                "»¤É½Ê¹Õß",
                "quest_type":           "É±",
                "exp_bonus":            101,
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            101,
        ]),
        ([      "quest":                "´óºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            101,
        ]),
//end 99k 
        ([      "quest":                "ïÚÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "Ê¯Ëø",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "Ð¡Ñ¾»·",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":               HIG"Ç³ÂÌÐ¡¹Ó"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "»ÆÉ½·ç¾°Í¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
//end 110k 

        ([      "quest":                "°¢¸£",
                "quest_type":           "É±",
                "exp_bonus":            120,
                "difficulty":           15,
        ]),
        ([      "quest":                "¾ÞÐÍÈ®",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "ÁõÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "»¨´ó¹Ã",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "»ôÓ¢",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "¶ÅÒ÷",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
//end 120k 
        ([      "quest":                "ÁÖÏÉ¶ù",
                "quest_type":           "É±",
                "exp_bonus":            132,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÒøºìÉ¢»¨È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
                "difficulty":           15,
        ]),
        ([      "quest":                "¾¢×°ÉÙÄê",
                "quest_type":           "É±",
                "exp_bonus":            132,

        ]),
        ([      "quest":                "¹«Ëï²»ÖÇ",
                "quest_type":           "É±",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂÉÙÅ®",
                "quest_type":           "É±",
                "difficulty":           25,
                "exp_bonus":            132,
        ]),
        ([      "quest":                "Çà´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
// end 132k 
        ([      "quest":                "Îý»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "¶ÁÇ§Àï",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":               HIY"Îå" + HIR"²Ê"NOR + "½ôÉíÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "ÀÏÊµºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "·¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),

        ([      "quest":                "´óºú×ÓºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]), 
//end 145k 
        ([      "quest":                "ºþÉÏÁø",
                "quest_type":           "É±",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ºì³ñÎèÆ÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ÁøÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ºþÉÏÔÂ",
                "quest_type":           "É±",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ÔÂÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "´äÓñÅýÅÃ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
//end 160k 
        ([      "quest":                "¶«·ç",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "ÄÏ·ç",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "Î÷·ç",

                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "±±·ç",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "Ð¡¾ê",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "ÆÆÀÃµÄ·Ûºì²¼ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            176,
        ]),
//end 176 
        ([      "quest":                "Ò¶Áé",
                "quest_type":           "É±",
                "exp_bonus":            192,
                "difficulty":           20,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            192,
        ]),
        ([      "quest":                "¹´»êÊ¹Õß",
                "quest_type":           "É±",
                "exp_bonus":            192,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÎÚÄ¾ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            192,
        ]),
        ([      "quest":                "°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            192,
        ]),
        ([      "quest":                "¹·ÀÉ¾ý",

                "quest_type":           "É±",
                "exp_bonus":            192,
                "difficulty":           25,
        ]), 
//end 192 
        ([      "quest":                "ÀîÉñÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "ÀÏÉ½Ñò",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "»ÆÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "°×ÅÛ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
//end 208 
        ([      "quest":                "Òõ±ö",
                "quest_type":           "É±",
                "exp_bonus":            225,
                "difficulty":           15,
        ]),
        ([      "quest":                HIR"ÇáºìÂÞç­ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            225,
        ]),
        ([      "quest":                "±öÅ«",
                "quest_type":           "É±",
                "exp_bonus":            225,
                "difficulty":           15,
        ]),
        ([      "quest":                HIR"ÇáºìÂÞç­É´"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            225,

        ]),
        ([      "quest":                "ËÎÖÐ",
                "quest_type":           "É±",
                "exp_bonus":            225,
        ]), 
//end 225 
        ([      "quest":                "Ð¡À¼",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶¾ÁúÉ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "Äµµ¤",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶¬Çà",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "Ãµ¹å",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶Å¾é",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
//end 242 
        ([      "quest":                "öÇÓãºâ±ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
        ]),
        ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
        ]),

        ([      "quest":                "°×¾±»ÒÐÜ",
                "quest_type":           "É±",
                "exp_bonus":            260,
                "difficulty":           15,
        ]),
        ([      "quest":                "¿ñæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            260,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÍÅ½ð¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
                "difficulty":           15,
        ]), 
//end 260 
        ([      "quest":                "´óÅ£",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Ï¹×Ó",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "·ÛÑà×Ó",
                "quest_type":           "É±",
                "exp_bonus":            280,
                "difficulty":           20,
        ]),
        ([      "quest":                "Í­Ç®ïÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Æ¤ÄÒ",
                "quest_type":           "Ñ°",

                "exp_bonus":            280,
        ]), 
//exp 280 
        ([      "quest":                "·½ÓñÏã",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "·½Óñ·É",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "ÀäÈôËª",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "Òø»¨Çàµ×Åû¼çÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "Òø»¨Çàµ×Åû¼çÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "À¶ºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]), 
//exp 303 
        ([      "quest":                "´¾ÓÚ»³Ì«",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "ÉßÁÛÆ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "½«¾ü",
                "quest_type":           "É±",
                "exp_bonus":            330,

                "difficulty":           20,
        ]),
        ([      "quest":                "½ð·ï»Ë",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "±Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),  
        ([      "quest":                "´äÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
//exp 330 
        ([      "quest":                "Ò¶Ñ©",
                "quest_type":           "É±",
                "exp_bonus":            362,
                "difficulty":           20,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            362,
        ]),
        ([      "quest":                "»¨¹Ñ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            362,
                "difficulty":           20,
        ]),
        ([      "quest":                "Íõ·ç",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),
        ([      "quest":                "°×ÀÏÈý",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),
        ([      "quest":                "Éò±Ú¾ý",
                "quest_type":           "É±",

                "exp_bonus":            362,
        ]), 
// exp 362 
        ([      "quest":                "óï·ÉÓê",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "ÖìÈ¸Õ½ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "»¨·É",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "Ê¥ÁéÅû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "óïÂü·ç",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "ÐþÎäÕ½ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
// exp 400 
        ([      "quest":                "·çËÄÄï",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "ÔÆÁ÷",
                "quest_type":           "É±",
                "exp_bonus":            440,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÐìÄï",
                "quest_type":           "É±",

                "exp_bonus":            440,
        ]),
        ([      "quest":                "ÃîÁäÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "²õÒíÉ´ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "Åã¾ÆÅ®",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]), 
// exp 440 
        ([      "quest":                "¹ÖÊÞ",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "°×¶îÃÍ»¢",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "ËÕºì¶ù",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "Ð¡Í¯",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":               HIY"Ç³»ÆÐ¡¹Ó"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "»¨Âú³Ç",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]), 

//exp 485k  
        ([      "quest":                "Á¦Ê¿",
                "quest_type":           "É±",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "½ð¸ÕèÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "±¦¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "È¸×Óº×",
                "quest_type":           "É±",
                "exp_bonus":            530,
        ]),   
        ([      "quest":                "¿ÕÉ÷",
                "quest_type":           "É±",
                "exp_bonus":            530,
                "difficulty":           15,
        ]),
        ([      "quest":                "Ñ¦ÍÓ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            530,
        ]), 
//end 530k  
        ([      "quest":                "ÔÆËÉ",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Äá°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Îå»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            580,
        ]),

        ([      "quest":                "ÆÕÉú",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "ÌÆ¿ÉÇä",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Àäºì¶ù",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]), 
// end 580k 
        ([      "quest":                "ËÄ´ü²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "Àî·ç",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "ÕÔÄÜ",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "Ìú´«¼×",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "³Ö¹úÌìÍõ",
                "quest_type":           "É±",
                "exp_bonus":            630,
                "difficulty":           20,
        ]),
        ([      "quest":                "Àµß¸µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
        ]), 
//end 630k 

        ([      "quest":                "Ëº³ÉÌõµÄ²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            680,
        ]),
        ([      "quest":                "Ì«°×ÒÝ",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
        ([      "quest":                "ÂÌÖé",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
        ([      "quest":                CYN"ÇàÒÂÉÙÅ®"NOR,
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
        ([      "quest":                CYN"Çà´ø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            680,
        ]),
        ([      "quest":                BLU"À¶ÒÂÉÙÅ®"NOR,
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
        ([      "quest":                BLU"À¶ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            680,
        ]),
//end 680k 
        ([      "quest":                HIR"³ÈÒÂÉÙÅ®"NOR,
                "quest_type":           "É±",
                "exp_bonus":            735,
        ]),
        ([      "quest":                HIR"³È½í"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            735,
        ]),
        ([      "quest":                GRN"ÂÌÒÂÉÙÅ®"NOR,
                "quest_type":           "É±",

                "exp_bonus":            735,
        ]),
        ([      "quest":                GRN"ÂÌÐ¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            735,
        ]),
        ([      "quest":                HIG"³¤Éú½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            735,
        ]),
        ([      "quest":                "¶àÇé»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            735,
        ]), 
//end 735k  
        ([      "quest":                "±í¸ç",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           35,
        ]),
        ([      "quest":                "ÎèÁø½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¹ËÔÆ·ÉµÄÃØº¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ò¶¹Âºè",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           20,
        ]),
        ([      "quest":                "°×½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Õ¼²·ÈëÃÅ",
                "quest_type":           "Ñ°",

                "exp_bonus":            20,
        ]),
//exp 790k 
        ([      "quest":                "ÎÞÃû·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "¼ÞÒÂÉñ¹¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "Öî¸ðÐ¡À×",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "ÍõïÚÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "·¨»ª¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "·¨º£²Ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            845,
        ]), 
//end 845k 
        ([      "quest":                "ÖñÒ¶Çà",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "°×»·",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "°×Ý¦",
                "quest_type":           "É±",
                "exp_bonus":            900,

        ]),
        ([      "quest":                "´÷Òú",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "Îå´ü²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "ºú²»³î",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
//end 900 
        ([      "quest":                "Çå·çÊ®ÈýÊ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÎºÐÐÁú",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
        ([      "quest":                HIR"ÏÊºìÒÂÉÑ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÀîºìÐä",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           20,
        ]),
        ([      "quest":                "Ôö³¤ÌìÍõ",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),

        ([      "quest":                "²©²æ³àË÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
//end 955 
});  
//Find the First Index to have exp level >= x
int Find(int x)
{
int total;
int low,high,now;
total=sizeof(quest); 
if(quest[0]["exp_bonus"]>=x)
 return 0;
if(quest[total-1]["exp_bonus"]<x)
 return total-1; 
low=0;
high=total-1;
now=(low+high)/2; 
while(high-low>1)
{
 if(quest[now]["exp_bonus"]>=x)
   high=now;
 else 
   low=now;
  
 now=(low+high)/2;
} 
return high;
} 

mapping query_quest(int exp)
{
  int a,b;
  
  a=Find(exp*8/10);
  b=Find(exp*16/10);
  

  if(a==b)
    return quest[a];
  else
    return quest[a+random(b+1-a)];
}        
