       ([      "quest":                "Ê¯Ñã",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "×Ï½ð¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "°ËØÔµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÆßÐÇ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "¸ðÂ×",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "¾Å»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "°×Ë®ÄïÄï",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "÷ÈÓ°Éñ½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "÷ÈÓ°Éñ´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "÷ÈÓ°ÉñÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "÷ÈÓ°ÉñÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÁÒ»ðÄõÁú",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "»ð¾ÞÁé",
                "quest_type":           "É±",
                "exp_bonus":            80,
        ]),
        ([      "quest":               HIR"»ðÑæ³¤µ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":                HIR"»ðÁú³àÆ¤"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":                "ÓðÌì°×",
                "quest_type":           "É±",
                "exp_bonus":            80,
        ]),
        ([      "quest":               HIG"Ð¡Â¥Ò»Ò¹Ìý´ºÓê"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":               HIW"°×ÓðÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),  
