#include <ansi.h>
inherit SKILL;
mapping *quest = ({ 
	
        ([      "quest":                "ËÉÊµ",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÇáË¿°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]),
        ([      "quest":                "¹¬ÄÏÑà",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
        ]),
		([      "quest":                "À×Ò»Ãù",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           55,
        ]),
        ([      "quest":                "ÔÆÁÖ",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
        ([      "quest":                HIW"È¥¹Çµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]),
        ([      "quest":                "¹ØÓñÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                 "difficulty":           20,
		]),
        ([      "quest":                "Î§Æå×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]), 
        ([      "quest":                "ÀÏÀÏ¸¾ÈË",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
        ([      "quest":                "ÎÞºÞÉú",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
        ([      "quest":                "Æ½·²ÉÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
        ([      "quest":                "»Û´óÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
        ([      "quest":                "Ò»³¾²»È¾µÄ°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]),  
        ([      "quest":                "ÆÆ¾É²»¿°µÄÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]),
        ([      "quest":                "×ÍÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]), 
        ([      "quest":                "Ç®²»×¬",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           40,
        ]),
        ([      "quest":                "Ç®²»Òª",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           40,
         ]),
        ([      "quest":                "×³ÄêºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           55,
         ]),
        ([      "quest":                "ºÚ²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
                 "difficulty":          10,
        ]),
        ([      "quest":                "ÀÏÉ®",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           75,
         ]),
        ([      "quest":                "»Ò²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
                "difficulty":           10,
        ]),
        ([      "quest":                "³àÑôµÀ³¤",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           30,
        ]),
        ([      "quest":                "Ë¿Ö¯µÄµÀ·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
                 "difficulty":           20,
        ]), 
        ([      "quest":                "»¨ËÄÒ¯",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           30,
        ]),
        ([      "quest":                "ÍõÓêÂ¥",
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
        ]),
        ([      "quest":                HIY"ÑÌÓêäìäì»·½ðÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            5660,
        ]), 
        ([      "quest":                HIY"½ð¼×ÎäÊ¿"NOR,
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
        ]),
        ([      "quest":                WHT"ÈËÐÎ¹ÖÎï"NOR,
                "quest_type":           "É±",
                "exp_bonus":            5660,
                "difficulty":           20,
         ]),
//end 5660
        ([      "quest":                "¹«Ò±³¤",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÇàÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                 "difficulty":           20,
        ]),  
        ([      "quest":                "ÖñóÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                 "difficulty":           20,
        ]),  
        ([      "quest":                "»ÒÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                 "difficulty":           20,
        ]), 
        ([      "quest":                "ÀÏµ¶°Ñ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           60,
         ]), 
        ([      "quest":                HIY"½ð¹âìøÕÈ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]), 
        ([      "quest":                "ÐË¹ú´óÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           75,
         ]),
        ([      "quest":                "ÉÏ¹Ù½ðºç",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           105,
         ]),
        ([      "quest":                "Áú·ïË«»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
       ([      "quest":                "¶¡³Ë·ç",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
       ([      "quest":                "¶¡°×ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
                ([      "quest":                "ÀÏ¼ÒÈË",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
        
        
        ([      "quest":                "ÅËÁæ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           88,
        ]),
        ([      "quest":                "ÀÖÀÖÉ½",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           88,
        ]),
        ([      "quest":                "»¨»¨µÀ³¤",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        ([      "quest":                "²É»¨·ä",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           88,
        ]),
        ([      "quest":                "ÇàÖñÉß",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           88,
        ]),
        ([      "quest":                "·ÉÌìÖ©Öë",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           66,
        ]),
        ([      "quest":                "Ä½ÈÝÃ÷Öé",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           66,
        ]),
        ([      "quest":                "¶ÀÑÛÁú",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           66,
        ]),
        ([      "quest":                "ºÃÐÄµÄ»ï¼Æ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
        ([      "quest":                "ÄÏ¹¬Ð¡µÜ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),
        
        
        ([      "quest":                "Ñ¦±ó",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        ([      "quest":                "ÌÒ»¨Äï×Ó",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           100,
        ]),
        ([      "quest":                "ÁËÒòÊ¦Ì«",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        ([      "quest":                YEL"ÌìÃÀ¹«Ö÷"NOR,
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           120,
        ]),
        ([      "quest":                "Ð»Ð¡Óñ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        ([      "quest":                "Ñ¦´óºº",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        
                ([      "quest":                "Áø¶«À´",
                "quest_type":           "É±",
                "exp_bonus":            6990,
                 "difficulty":           300,
        ]), 
        ([      "quest":                "Ô¬ÇïÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            6990,
                 "difficulty":           300,
        ]), 
        ([      "quest":                "Ô¬ÇïÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            8990,
                 "difficulty":           200,
        ]), 
        ([      "quest":                "Ô¬ÇïÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            10990,
                 "difficulty":           100,
        ]), 

        ([      "quest":                "Áø¶«À´",
                "quest_type":           "É±",
                "exp_bonus":            8990,
                 "difficulty":           200,
        ]), 
        
        ([      "quest":                "Áø¶«À´",
                "quest_type":           "É±",
                "exp_bonus":            10990,
                 "difficulty":           100,
        ]), 
        
        ([      "quest":                "¾ÅÐÇ·­ÔÆÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "Áù¸ùÇå¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "µØÆìµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "è·½£Íõ·ò",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "ÌìÊ¦µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "ÈýÇåÉñ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]), 
        ([      "quest":                "Öä½£Íõ·ò",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           10,
        ]),
        ([      "quest":                HIG"Óñ»·µ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]), 
        ([      "quest":                HIG"Óñ»·½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]), 
        ([      "quest":                HIG"Óµ´äÈ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           30,
        ]),  
        ([      "quest":                "ÀîÓñº¯",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           105,
        ]),
        ([      "quest":                "ÁøÎÞÃ¼",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           105,
        ]),
        ([      "quest":                HIW"Òø¼×"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                HIY"½ð¿ø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                "³£Ê¤½«¾ü",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           35,
        ]),
        ([      "quest":                "¼Ð×ÅÎå»¨ÈâµÄÂøÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           20,
        ]), 
        ([      "quest":                "¼¦¹ÇÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           20,
        ]), 
        ([      "quest":                "²¼Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           20,
        ]), 
        ([      "quest":                BLU"³ñ¶ÐÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           20,
        ]),  
        ([      "quest":                "ÅÖ¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]), 
        ([      "quest":                HIB"ÇàÄ§ÊÖ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                CYN"Çà²¼³¤ÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                "¸ßÃ±×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                "ÒÁ¿Þ",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           50,
        ]),
        ([      "quest":                HIG"Ð¡Â¥Ò»Ò¹Ìý´ºÓê"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]), 
        ([      "quest":                HIW"°×ÓðÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            6660,
                "difficulty":           25,
        ]),
        ([      "quest":                "ÓðÌì°×",
                "quest_type":           "É±",
                "exp_bonus":            6660,
                "difficulty":           45,
        ]),
//end 6660





        ([      "quest":                HIG"Á¬³Çèµ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           45,
        ]),
        ([      "quest":                "ÏôÊ®Ò»ÀÉ",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           380,
        ]),
        ([      "quest":                HIR"¸îÂ¹µ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           350,
        ]),
        
        
        ([      "quest":                HIG"»¹»ê²Ý"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           25,
        ]),
        ([      "quest":                HIY"»Æ½ðÃæ¾ß"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           25,
        ]),
        ([      "quest":                "ÎÂÁ¼Óñ",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           55,
        ]),
        ([      "quest":                "ÑÔÇàÒÂ",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           60,
        ]),
        ([      "quest":                "»ªÕæÕæ",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           90,
        ]),
        ([      "quest":                "Çå·ç½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           40,
        ]), 
        
        ([      "quest":                YEL"¹ü²¼Ä¾¹÷"NOR, 
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           105,
        ]), 
        ([      "quest":                HIY"¶ì»ÆÈ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           40,
        ]), 
        ([      "quest":                "Ð»Ïþ·å",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           150,
        ]),
        ([      "quest":                "»ªÉÙÀ¤",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           125,
        ]),
        ([      "quest":                "ÈýÉÙÒ¯µÄ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           100,
        ]), 
        ([      "quest":                HIR"°ó×ÅÒ»¿éÄ¾Í·µÄÐâÌúÆ¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]),
        ([      "quest":                "°¢·É",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           60,
        ]), 
        ([      "quest":                "ÓñÀ¼Ïª",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           50,
        ]),
        ([      "quest":                "ÌÆÒ»·½",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           70,
        ]),
        ([      "quest":                "³þÁôÏã",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           50,
        ]),
        ([      "quest":                HIM"Ìì²ÏË¿´ø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]),
        ([      "quest":                HIW"°×»¢Ö®îø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]),
        ([      "quest":                HIC"ÇàÁú±¦¼×"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]),
        ([      "quest":                HIR"÷ÈÓ°ÉñÑ¥"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7260,
                "difficulty":           30,
        ]),
        ([      "quest":                "óïÍõËï",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           70,
        ]),
//end 7260



/*
8m new quest add here
*/

        ([      "quest":                "°×Ë®ÄïÄï",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           95,
        ]),
        ([      "quest":                "÷ÈÓ°Éñ½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                "difficulty":           40,
        ]),
        ([      "quest":                "÷ÈÓ°Éñ´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                "difficulty":           40,
        ]),
        ([      "quest":                "÷ÈÓ°ÉñÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                "difficulty":           40,
        ]),
        ([      "quest":                "÷ÈÓ°ÉñÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                "difficulty":           40,
        ]),
        ([      "quest":                "ÇØ¸è",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                 "difficulty":           30,
        ]),
        	([      "quest":                HIR"ÑªºìË¿½í"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           50,
        ]),  
        ([      "quest":                HIR"ÑªºìË¿½í"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           50,
        ]),  
        ([      "quest":                HIR"ÑªºìË¿½í"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           50,
        ]),  
		([      "quest":                CYN"Ä«×Ó½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           50,
        ]),  
        ([      "quest":                "Ò¶¹Â³Ç",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           150,
        ]),
        ([      "quest":                "Î÷ÃÅ´µÑ©",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                 "difficulty":           100,
        ]), 
        ([      "quest":                HIR"º®Ìì´µÑª"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           40,
        ]),  
        ([      "quest":                "º®Ìì±ùÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           40,
        ]), 
        ([      "quest":                "ÓÝ¼§½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           40,
        ]), 
        ([      "quest":                "ÛòÏÂµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           40,
        ]),
        ([      "quest":                "´Ö²¼¶ì»ÆÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           40,
        ]),
        ([      "quest":                "Ñ©Èï¶ù",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           105,
        ]),
        ([      "quest":                "ÌúÉÙ",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           105,
        ]),
        ([      "quest":                RED"´óºì²¼ÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           30,
        ]),
        ([      "quest":                "ÀîºìÅÛ",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           60,
        ]), 
//end of 9260              
//ËùÓÐÄÑ¶È³¬¹ý300µÄ¶¼µ÷Õû
 ([      "quest":                 "¸µºìÑ©",
                "quest_type":           "É±",
                "exp_bonus":            9999,
                "difficulty":           200,
        ]),
        ([      "quest":                 "Âí¿ÕÈº",
                "quest_type":           "É±",
                "exp_bonus":            9999,
                "difficulty":           250,
        ]),
        
([      "quest":                "ÆáºÚµÄµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           150,
        ]),
        
        ([      "quest":                "ÆáºÚµÄÐ¡µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           250,
        ]),
        
        ([      "quest":                "³þÁôÏã",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           50,
        ]),
        ([      "quest":                "óïÍõËï",
                "quest_type":           "É±",
                "exp_bonus":            7260,
                "difficulty":           70,
        ]),
               
		([      "quest":                CYN"Ä«×Ó½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9260,
                 "difficulty":           50,
        ]),  
        ([      "quest":                "Ò¶¹Â³Ç",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           150,
        ]),
        ([      "quest":                "Î÷ÃÅ´µÑ©",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                 "difficulty":           120,
        ]), 
             ([      "quest":                "ºÚÎÞ³£",
                "quest_type":           "É±",
                "exp_bonus":            8990,
                "difficulty":           50,
        ]),

        ([      "quest":                "°×ÎÞ³£",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           120,
        ]),
		([      "quest":                "¸Ö²æ",
                "quest_type":           "Ñ°",
                "exp_bonus":            8260,

        ]),  

         ([      "quest":                "Ñ©Èï¶ù",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           105,
        ]),
        ([      "quest":                "ÌúÉÙ",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           125,
        ]),
        
        ([      "quest":                "ÀîºìÅÛ",
                "quest_type":           "É±",
                "exp_bonus":            9260,
                "difficulty":           100,
        ]), 
        
        ([      "quest":                "ÑàÊ®ÈýµÄ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           80,
        ]), 
        ([      "quest":                "ºÚÉ«³¤ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           50,
        ]), 
        ([      "quest":                "ºÚÉ«Ãæ½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           50,
        ]), 
        ([      "quest":                "ÑàÊ®Èý",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           300,
        ]),
        ([      "quest":                MAG"å«º£ÔÆÑÌ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           120,
        ]), 
        ([      "quest":                HIY"½ðË¿Èí¼×"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           120,
        ]), 
        ([      "quest":                "Ô­ËæÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           400,
        ]),
        ([      "quest":                "»ÆÂé×Ó",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           300,
        ]),
        ([      "quest":                "÷½×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           100,
        ]), 
        ([      "quest":                HIY"ÅÌ¹Å¿ªÌì¸«"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           120,
        ]),  
        ([      "quest":                HIM"×ÏòþÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           120,
        ]), 
        ([      "quest":                "¿ì»îÍõ",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           400,
        ]),  
        ([      "quest":                HIG"¶ÏÃÅ½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           120,
        ]), 
        ([      "quest":                "ÉòÀË",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           200,
        ]),
        ([      "quest":                "½£Å«",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                "difficulty":           100,
        ]),
        ([      "quest":                "Ê¯Ñã",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                 "difficulty":           500,
        ]),
        ([      "quest":                "×Ï½ð¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           200,
        ]),
        ([      "quest":                "°ËØÔµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           200,
        ]),
        ([      "quest":                "ÆßÐÇ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           200,
        ]),
        ([      "quest":                "²«ÀË´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           200,
        ]),
        ([      "quest":                "¾ÞãÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           200,
        ]),

  ([      "quest":                HIY"¿×È¸ôá"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9990,
                 "difficulty":           100,
        ]),
        ([      "quest":                "ÖìÎåÌ«Ò¯",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                 "difficulty":           500,
        ]),
        ([      "quest":                "¼§Ôá»¨",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                 "difficulty":           400,
        ]),
        
        ([      "quest":                "ºÚ´ø",
                "quest_type":           "É±",
                "exp_bonus":            9990,
                 "difficulty":           500,
        ]),
   //ÔÝÊ±È¡ÏûÏÂÃæµÄÈçºÎ£¿     
 /*       ([      "quest":                HIY"ÕæÎäµÛ¾ý"NOR,
                "quest_type":           "É±",
                "exp_bonus":            9999,
                 "difficulty":           800,   
        ]),
        
        ([      "quest":                "´ïÄ¦Ãæ±ÚÏñ",
                "quest_type":           "É±",
                "exp_bonus":            9999,
                 "difficulty":           800,              
        ]),
        
        ([      "quest":                "ò¿ÓÈ",    
                "quest_type":           "É±",
                "exp_bonus":            9999,
                 "difficulty":           800, 
        ]),  */
//end of 9990 - final
}); 
//Find the First Index to have exp level >= x
int Find(int x)
{
        int total;
        int low,high,now;
        total=sizeof(quest); 
        if(quest[0]["exp_bonus"]>=x)
                return 0;
        if(quest[total-1]["exp_bonus"]<x)
                return total-1; 
        low=0;
        high=total-1;
        now=(low+high)/2; 
        while(high-low>1) {
                if(quest[now]["exp_bonus"]>=x)
                        high=now;
                else 
                        low=now;
                now=(low+high)/2;
        }
        return high;
} 
mapping query_quest(int exp)
{
        int a,b,c; 
        int low,high; 
        
        if (exp>=15000) {
                low=9200;
                high = 10000;
        } else if (exp>10000) {
                low=7200;
                high=9300;
        } else if (exp>8000) {
                low=6600;
                high=exp+300;
        } else {
                low=5600;
                high=exp+200;
        } 
        //if(low>5000) low=5000;   
        //if(high<3) high=3; 
        a=Find(low);
        b=Find(high)-1;
        c=a+random(b+1-a);
        return quest[c];
} 
int TotalNumber()
{
        return sizeof(quest);
} 
int KillNumber()
{
        int count=0;
        int i,total;
        total=sizeof(quest);
        for(i=0;i<total;i++) {
                if (quest[i]["quest_type"]=="É±") count++;
        }
        return count;
}
