#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ËÕÈØÈØ",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ð»³¤ÇÚ",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           20,
        ]),
        ([      "quest":                "Ò¶áç",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           85,
        ]),
        ([      "quest":                "Ò¶Óð",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           50,
        ]),
        ([      "quest":                "Àî³¤É÷",
                "quest_type":           "É±",
                "exp_bonus":            85,
                "difficulty":           20,
        ]),
        ([      "quest":                "¹©Ïã",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ì«¼«È­Á·¹¦Í¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Óü×ä",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ð¡ÌÒºì",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),        
        ([      "quest":                "·Ûºì°À",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
//end 85k
        ([      "quest":                "¹³Á¬Ç¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "ÎäÁÖ´óºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "Ìú»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "Í­»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "½ð·ç",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "½ðÓê",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "½ðÒ»",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]), 
        ([      "quest":                "½ð¶þ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),  
	([	"quest":		"Ò»¾ß¿ÝÇ¬µÄº¡¹Ç",
		"quest_type":		"Ñ°",
                "exp_bonus":		89,
	]),
	([	"quest":		"ÉáÀû×Ó",
		"quest_type":		"Ñ°",
                "exp_bonus":		89,
	]),
//end 89k
        ([      "quest":                "ºÚ¹Ú¾Þòþ",
                "quest_type":           "É±",
                "exp_bonus":            93,
                "difficulty":           15,
        ]),
        ([      "quest":                "Öª¿ÍµÀÈË",
                "quest_type":           "É±",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "»ÆÉ«µÀ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "Çà²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
	([	"quest":		"ÀÏºÍÉÐ",
		"quest_type":		"É±",
		"exp_bonus":		100,
	]),
	([	"quest":		"°×ÃÞôÂôÄ",
		"quest_type":		"Ñ°",
                "exp_bonus":		100,
	]),
	([	"quest":		"ÄÏ¹¬Ê®ÈýÀÉ",
		"quest_type":		"É±",
		"exp_bonus":		100,
	]),
	([	"quest":		"ºìÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		100,
	]),
	([	"quest":		"°ÙÀïÁé",
		"quest_type":		"É±",
		"exp_bonus":		100,
	]),
	([	"quest":		"ËÎÖÐ",
		"quest_type":		"É±",
		"exp_bonus":		100,
	]),
// end 100k
	([	"quest":		"ÖóÊìÁËµÄÇù",
		"quest_type":		"Ñ°",
                "exp_bonus":		105,
	]),
        ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "Íäµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "´óºì²¼ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "»¤É½Ê¹Õß",
                "quest_type":           "É±",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "´óºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            105,
        ]),
	([	"quest":		"¾«ÖÂÄñÁý",
		"quest_type":		"Ñ°",
                "exp_bonus":		105,
	]),
        ([      "quest":                "ÔÀÑó",
                "quest_type":           "É±",
                "exp_bonus":            105,
        ]),
//end 105k
	([	"quest":		"¹ÅËÉÇÙ",
		"quest_type":		"Ñ°",
		"exp_bonus":		110,
	]),
	([	"quest":		"Àî±ª",
		"quest_type":		"É±",
		"exp_bonus":		110,
	]),
        ([      "quest":                "ïÚÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "Ê¯Ëø",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                WHT"»ÆÉ½·ç¾°Í¼"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
	([	"quest":		"½ðË¿È¸",
		"quest_type":		"É±",
		"exp_bonus":		110,
	]),
//end 110k
	([	"quest":		"´äÓñÅýÅÃ",
		"quest_type":		"Ñ°",
                "exp_bonus":		120,
	]),
	([	"quest":		"Îå²ÊÉñÏÉÓã",
		"quest_type":		"É±",
		"exp_bonus":		120,
	]),
        ([      "quest":                "°¢¸£",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "¾ÞÐÍÈ®",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
           
        ([      "quest":                "ÁõÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "»ôÓ¢",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "¶ÅÒ÷",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "Ö½Ìõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            120,
        ]),
  	([	"quest":		"ÃÏÆÅ",
		"quest_type":		"É±",
		"exp_bonus":		120,
	]),
//end 120k
	([	"quest":		"°¬Èý",
		"quest_type":		"Ñ°",
                "exp_bonus":		130,
	]),
	([	"quest":		RED"Ò°¹û"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		130,
	]),
	([	"quest":		"»¢¹Ç",
		"quest_type":		"Ñ°",
                "exp_bonus":		130,
	]),
	([	"quest":		BLK"ºÚÑ¥"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		130,
	]),
	([	"quest":		BLK"ºÚÉ´"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		130,
	]),
        ([      "quest":                "¾¢×°ÉÙÄê",
                "quest_type":           "É±",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "¹«Ëï²»ÖÇ",
                "quest_type":           "É±",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂÉÙÅ®",
                "quest_type":           "É±",
                "difficulty":           15,
                "exp_bonus":            132,
        ]),
        ([      "quest":                "Çà´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "Âä»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),        
// end 132k
	 
	([	"quest":		HIC"Æß"HIB"²Ê"HIG"º£"HIY"ÂÝ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		140,
	]),
        ([      "quest":                "Îý»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "¶ÁÇ§Àï",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "ÀÏÊµºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([	"quest":		HIR"Æß"+HIY"²Ê"+HIG"Ë¿¶Ð´ø"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		110,
	]),
        ([      "quest":                "·¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "´óºú×ÓºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
	([	"quest":		"ºÚ´ÉÒ©ÎÍ",
		"quest_type":		"Ñ°",
                "exp_bonus":		150,
	]),
	([	"quest":		"Í­·ð¹Ä",
		"quest_type":		"Ñ°",
                "exp_bonus":		150,
	]),
	([	"quest":		"Ìú¿²",
		"quest_type":		"É±",
		"exp_bonus":		150,
	]),
	([	"quest":		"ÌúÁ¦",
		"quest_type":		"É±",
		"exp_bonus":		150,
	]),
//end 150k
        ([      "quest":                "ºþÉÏÁø",
                "quest_type":           "É±",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ºì³ñÎèÆ÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ÁøÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ºþÉÏÔÂ",
                "quest_type":           "É±",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "ÔÂÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([      "quest":                "°×ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            160,
        ]),
        ([	"quest":		BLK"ºÚ±Þ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		160,
	]),
	([	"quest":		BLK"ºÚÅÛ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		160,
	]),                     
//end 160k
	
	([	"quest":		"æÒÐ¡Èá",
		"quest_type":		"É±",
		"exp_bonus":		170,
	]),
	([	"quest":		"æÒÐ¡Áá",
		"quest_type":		"É±",
		"exp_bonus":		170,
	]),
	([	"quest":		HIG"ÇáÉ´³¤È¹"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		170,
	]),
	([	"quest":		"ÑªÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		170,
	]),
	([	"quest":		"Ð¡½ð¸Õ¾­",
		"quest_type":		"Ñ°",
                "exp_bonus":		170,
	]),
	([	"quest":		"Ð¡³Ë¾­",
		"quest_type":		"Ñ°",
                "exp_bonus":		170,
	]),
        ([      "quest":                "±±·ç",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "Ð¡¾ê",
                "quest_type":           "É±",
                "exp_bonus":            176,
        ]),
        ([      "quest":                "ÆÆÀÃµÄ·Ûºì²¼ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            176,
        ]),

//end 176
	([	"quest":		YEL"À°³¦"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		180,
	]),
	([	"quest":		RED"Â±ÖíÉà"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		180,
	]),
	([	"quest":		"Ë¿³ñÂí¹Ó",
		"quest_type":		"Ñ°",
                "exp_bonus":		180,
	]),
	([	"quest":		"´ó½ð¸Õ¾­",
		"quest_type":		"Ñ°",
                "exp_bonus":		180,
	]),
        ([      "quest":                "Ò¶Áé",
                "quest_type":           "É±",
                "exp_bonus":            192,
                "difficulty":           20,
        ]),
        ([      "quest":                "¹´»êÊ¹Õß",
                "quest_type":           "É±",
                "exp_bonus":		192,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÎÚÄ¾ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            192,
        ]),
        ([      "quest":                "°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            192,
        ]),
        ([      "quest":                "¹·ÀÉ¾ý",
                "quest_type":           "É±",
                "exp_bonus":            192,
                "difficulty":           20,
        ]),
        
//end 192
	([	"quest":		"³ÇÚòÓ¡",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"Í­·ðÖÓ",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"æÒÐ¡²·",
		"quest_type":		"É±",
		"exp_bonus":		200,
	]),
	([	"quest":		"¶Ì¿ãÍ·",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"ÆßÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"°ËÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"¾ÅÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"Ò»Í°",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"¶þÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"ÈýÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"ÁùÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"ÎåÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		200,
	]),
	([	"quest":		"ºìÖÐ",
		"quest_type":		"É±",
		"exp_bonus":		200,
	]),
        ([      "quest":        	"Àî·ç",
                "quest_type":           "É±",
                "exp_bonus":            200,
        ]),
        ([      "quest":                "ÀîÉñÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "ÀÏÉ½Ñò",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "»ÆÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
        ([      "quest":                "°×ÅÛ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            208,
        ]),
	([	"quest":		"Äù°ã¾­",
		"quest_type":		"Ñ°",
                "exp_bonus":		208,
	]),
	([	"quest":		"´µÑ©²ÐÔÆ½í",
		"quest_type":		"Ñ°",
                "exp_bonus":		220,
	]),
	([	"quest":		"´µÑ©²ÐÔÆ´ø",
		"quest_type":		"Ñ°",
                "exp_bonus":		220,
	]),
	([	"quest":		"ÎÂÐÁ",
		"quest_type":		"É±",
		"exp_bonus":		220,
	]),
	([	"quest":		"ÎÂºÍ",
		"quest_type":		"É±",
		"exp_bonus":		220,
	]),
	([	"quest":		"ÎÂÎÄ",
		"quest_type":		"É±",
		"exp_bonus":		220,
	]),
	([	"quest":		"ÎÂË³",
		"quest_type":		"É±",
		"exp_bonus":		220,
	]),
	([	"quest":		"Ïãß¡ÉÈ",
		"quest_type":		"Ñ°",
                "exp_bonus":		220,
	]),
	([	"quest":		"¸îÆ¤Ð¡µ¶",
		"quest_type":		"Ñ°",
                "exp_bonus":		220,
	]),
	([	"quest":		"ÕÅÁû×Ó",
		"quest_type":		"É±",
		"exp_bonus":		220,
	]),

        ([      "quest":                HIR"ÇáºìÂÞÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            225,
        ]),
        ([      "quest":                "±öÅ«",
                "quest_type":           "É±",
                "exp_bonus":            225,
        ]),
        
//end 225


	
	([	"quest":		"´µÑ©²ÐÔÆÑ¥",
		"quest_type":		"Ñ°",
                "exp_bonus":		242,
	]),
        ([      "quest":                "Ð¡À¼",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶¾ÁúÉ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "Äµµ¤",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶¬Çà",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "Ãµ¹å",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "¶Å¾é",
                "quest_type":           "É±",
                "exp_bonus":            242,
        ]),
        ([      "quest":                "ËÄ´ü²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            242,
        ]),
	([	"quest":		"ËÄÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		242,
	]),
	([	"quest":		"Î÷·ç",
		"quest_type":		"É±",
		"exp_bonus":		242,
	]),
//end 242
        ([      "quest":                "öÇÓãºâ±ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
        ]),
        ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
        ]),
        ([      "quest":                "¿ñæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            260,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÍÅ½ð¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            260,
                "difficulty":           15,
        ]),
	([      "quest":                "Ð¡Áå¶ù",
                "quest_type":           "É±",
                "exp_bonus":            260,
        ]),
	([	"quest":		"°ËÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"¾ÅÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"Ò»Í°",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"ÎåÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"ÈýÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"ÁùÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"¾ÅÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		260,
	]),
	([	"quest":		"ºìÖÐ",
		"quest_type":		"É±",
		"exp_bonus":		260,
	]),
//end 260
	([	"quest":		"Óñ½äÖ¸",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
        ([      "quest":                "´óÅ£",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Ï¹×Ó",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "·ÛÑà×Ó",
                "quest_type":           "É±",
                "exp_bonus":            280,
                "difficulty":           20,
        ]),
        ([      "quest":                "Í­Ç®ïÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            280,
        ]),
        ([      "quest":                "Æ¤ÄÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            280,
        ]),
        ([      "quest":                GRN"´äÖñÇ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            280,
        ]),
        ([      "quest":                HIG"ÏãÀæ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            280,
        ]),
	([	"quest":		"°ËÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"¾ÅÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"Ò»Í°",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"¶þÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"ÈýÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"ÁùÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"ÎåÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		280,
	]),
	([	"quest":		"¶«·ç",
		"quest_type":		"É±",
		"exp_bonus":		280,
	]),
//exp 280
        ([      "quest":                "Ç¹·¨¼ò½é",
                "quest_type":           "Ñ°",
                "exp_bonus":            300,
        ]),
        ([      "quest":                "Ä¾ºÐ×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            300,
        ]),
        ([      "quest":                "»¨´ó¹Ã",
                "quest_type":           "É±",
                "exp_bonus":            300,
        ]),
	([	"quest":		"²ÐÆÆµÄÅ®×ÓÄÚÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		300,
	]),
	([	"quest":		"ËÕºì¶ù",
		"quest_type":		"É±",
		"exp_bonus":		300,
	]),
	([	"quest":		"ÑÏÈËÓ¢",
		"quest_type":		"É±",
		"exp_bonus":		300,
	]),
	([	"quest":		HIM"·Ûºì³ñÉÀ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		300,
	]),
        ([      "quest":                "·½ÓñÏã",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "·½Óñ·É",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        ([      "quest":                "ÀäÈôËª",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),
        
        ([      "quest":                "À¶ºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            303,
        ]),

	([	"quest":		"ÔÆËØÃÜº¯",
		"quest_type":		"Ñ°",
                "exp_bonus":		310,
	]),
	([	"quest":		"ºÚÕäÖé",
		"quest_type":		"É±",
		"exp_bonus":		310,
	]),
	([	"quest":		"´ó³Ë¾­",
		"quest_type":		"Ñ°",
                "exp_bonus":		310,
	]),
	
//end 310
        ([      "quest":                "´¾ÓÚ»³Ì«",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "ÉßÁÛÆ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "½«¾ü",
                "quest_type":           "É±",
                "exp_bonus":            330,
                "difficulty":           20,
        ]),
        ([      "quest":                "½ð·ï»Ë",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                HIG"±Ì½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),  
        ([      "quest":                "´äÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "ÀÇÆ¤Åû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "ÆëÐ¡Ñà",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                "ËÎÌð¶ù",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),
        ([      "quest":                YEL"¶ì»ÆÉ«³¤È¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                YEL"ÀÇÈâ¸¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),
        ([      "quest":                WHT"ÀÇºÁ±Ê"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            330,
        ]),  
        ([      "quest":                "¸çÊæÕ½",
                "quest_type":           "É±",
                "exp_bonus":            330,
        ]),              
	([	"quest":		"Öñ¹Ü",
		"quest_type":		"Ñ°",
                "exp_bonus":		340,
	]),
	([	"quest":		"³£ÀÏ´ó",
		"quest_type":		"É±",
                "exp_bonus":		340,
	]),
	([	"quest":		"È¸×Óº×",
		"quest_type":		"É±",
                "exp_bonus":		340,
	]),
	
	([	"quest":		"°ËÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"¾ÅÍò",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"Ò»Í°",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"¶þÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"ÈýÍ°",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"ÁùÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"ÎåÌõ",
		"quest_type":		"Ñ°",
                "exp_bonus":		330,
	]),
	([	"quest":		"ºìÖÐ",
		"quest_type":		"É±",
		"exp_bonus":		330,
	]),
//exp 330
        ([      "quest":                "ÂäÆÇÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           25,
        ]),
	([      "quest":                "²Ë»¨Éß",
                "quest_type":           "É±",
                "exp_bonus":            350,
        ]),
	([	"quest":		RED"ÀÇ¾Æ´ü"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		350,
	]),
	([	"quest":		GRN"ÀÇÉ½²è"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		350,
	]),
        ([      "quest":                "Ò¶Ñ©",
                "quest_type":           "É±",
                "exp_bonus":            362,
                "difficulty":           20,
        ]),
        ([      "quest":                "»¨¹Ñ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            362,
                "difficulty":           20,
        ]),
        ([      "quest":                "Íõ·ç",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),
        ([      "quest":                "¾Þ»¨òþ",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),
        ([      "quest":                "ÍØ°ÏÕ½",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),        
	([      "quest":                "Ð¡Ááçç",
                "quest_type":           "É±",
                "exp_bonus":            362,
        ]),    
	([	"quest":		"ÓñÖé»¨",
		"quest_type":		"Ñ°",
                "exp_bonus":		380,
	]),
	([	"quest":		"Óñ·¢ô¢",
		"quest_type":		"Ñ°",
                "exp_bonus":		380,
	]),
	([      "quest":                "ºÎÑÅ·ç",
                "quest_type":           "É±",
                "exp_bonus":            380,
        ]),
// exp 380
	([	"quest":		"·ç¾ÅÓÄ",
		"quest_type":		"É±",
                "exp_bonus":		400,
	]),
	([	"quest":		"Ê÷Ò¶",
		"quest_type":		"Ñ°",
                "exp_bonus":		400,
	]),
	([	"quest":		HIY"³ÈÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		400,
	]),
	([	"quest":		"³Â×¼",
		"quest_type":		"É±",
		"exp_bonus":		400,
	]),
	([	"quest":		"ÐìÈýÒ¯",
		"quest_type":		"É±",
		"exp_bonus":		400,
	]),
	([	"quest":		"³¤Ç¹",
		"quest_type":		"Ñ°",
                "exp_bonus":		400,
	]),
	([	"quest":		"°×½£",
		"quest_type":		"Ñ°",
                "exp_bonus":		400,
	]),
        ([      "quest":                "óï·ÉÓê",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "ÖìÈ¸Õ½ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "»¨·É",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "Ê¥ÁéÅû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "óïÂü·ç",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                "ÐþÎäÕ½ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":        	"´÷Òú",
                "quest_type":           "É±",
                "exp_bonus":            400,
        ]),
        ([      "quest":                GRN"ËØæý³¤È¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
        ([      "quest":                HIY"½ðµ°"NOR ,
                "quest_type":           "Ñ°",
                "exp_bonus":            400,
        ]),
// exp 400
	([	"quest":		"¶«ÈýÄï",
		"quest_type":		"É±",
		"exp_bonus":		420,
	]),
	([	"quest":		"²ÆÊå",
		"quest_type":		"É±",
		"exp_bonus":		420,
	]),
	([	"quest":		"¼§ÁéÑà",
		"quest_type":		"É±",
		"exp_bonus":		420,
	]),
	([	"quest":		"¶ñÄ§",
		"quest_type":		"É±",
		"exp_bonus":		420,
	]),
	([	"quest":		"ÖÓÀëÕ½",
		"quest_type":		"É±",
		"exp_bonus":		420,
	]),
	([	"quest":		"ÂÊÒâÍ¼",
		"quest_type":		"Ñ°",
		"exp_bonus":		420,
	]),
        ([      "quest":                "·çËÄÄï",
                "quest_type":           "É±",
               "exp_bonus":            440,
        ]),
        ([      "quest":                "ÔÆÁ÷",
                "quest_type":           "É±",
                "exp_bonus":            440,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÐìÄï",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "ÃîÁäÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "Åã¾ÆÅ®",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "ÆáµñÕ½",
                "quest_type":           "É±",
                "exp_bonus":            440,
        ]),
        ([      "quest":                "Îå´ü²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
	([	"quest":		RED"ºìÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		450,
	]),
	([	"quest":		"Ð¡»­Í¯",
		"quest_type":		"É±",
                "exp_bonus":		450,
	]),
	([	"quest":		"Ð¡ÊéÍ¯",
		"quest_type":		"É±",
                "exp_bonus":		450,
	]),
// exp 440
	([	"quest":		"ÌÆ¿ÉÇä",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"Àäºì¶ù",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ÌìÎÞµ¶",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ÌìÎÞ½£",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"Ìì»¢",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ÄÏ·ç",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"¶«·ç",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"Ìì·Ê",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ÌìÊÞ",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ºú²»³î",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
	([	"quest":		"ÍÕ×ÓÀ®Âï",
		"quest_type":		"É±",
		"exp_bonus":		480,
	]),
        ([      "quest":                "¹ÖÊÞ",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "Ð¡Í¯",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":		HIY"Ç³»ÆÐ¡¹Ó"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "Ð¡ÆåÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
        ([      "quest":                "Ð¡ÇÙÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            485,
        ]),
	([      "quest":                "½õ²á",
                "quest_type":           "Ñ°",
                "exp_bonus":            485,
 	]),               
//exp 485k
	([	"quest":		YEL"»ÆÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		500,
	]),
        ([      "quest":                "ËïÍÕ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            500,
        ]),
	([	"quest":		"ËïÐ¡ºì",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
        ([      "quest":                "½ð»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            500,
        ]),
        ([      "quest":                HIR"ºìÂìÒÏ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            500,
        ]),
	([	"quest":		"Ñ¦ÍÓ×Ó",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
     	([	"quest":		HIY"³ÈÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		YEL"»ÆÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		GRN"ÂÌÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		CYN"ÇàÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		BLU"À¶Ð¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		MAG"×ÏÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		RED"ºìÐ¬"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		"³þ³þ",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
	([	"quest":		"½ðÍ¯",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
        ([      "quest":                "Ð¡½ð¸Õ",
                "quest_type":           "É±",
                "exp_bonus":            500,
        ]),              
	([	"quest":		"Ð¡Ñ¾»·",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
	([	"quest":		HIG"Ç³ÂÌÐ¡¹Ó"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		"»ðÅÚÍè",
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		"Ì«¼«°ËØÔµÀÅÛ",
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		"ÔÀÁÛ",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
	([	"quest":		HIB"ÎäÊ¿Åû·ç"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		500,
	]),
	([	"quest":		"Æ¤ÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		500,
	]),
	([	"quest":		"ºìÐÓ»¨",
		"quest_type":		"É±",
		"exp_bonus":		500,
	]),
        ([      "quest":                "Á¦Ê¿",
                "quest_type":           "É±",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "½ð¸ÕèÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "±¦¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            530,
        ]),
        ([      "quest":                "ÏãÏã",
                "quest_type":           "É±",
                "exp_bonus":            530,
        ]),       
	([	"quest":		HIY"³ÈÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		GRN"ÂÌÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		CYN"ÇàÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		BLU"À¶Ã±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		MAG"×ÏÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		YEL"»ÆÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
	([	"quest":		RED"ºìÃ±"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		530,
	]),
//end 530k
	([	"quest":		GRN"ÂÌÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		550,
	]),
	([	"quest":		"ÀÏÉ½¶«",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"Ôà²¼ÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"ÀÏÉ½¶«µÄÃæ¾ß",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"¾«¸ÖÔ°Í°",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"ÂÞÉ²ÅÆ",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"¡¸Ò×¾­¡¹",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		HIY"³È´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		GRN"ÂÌ´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		CYN"Çà´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		BLU"À¶´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	
	([	"quest":		"Ð¡»¹µ¤",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"Èý±¦É¢",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"»ØÌìÉ¢",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"Ãû¹ó²¹Æ·",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),

	([      "quest":                HIW"½­ÑÀº£Ë®°×òþÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([      "quest":                HIC"ïÎÒø¹¬ÌÐ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([      "quest":                BLU"¹ãÐäºÏ»¶°À"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([	"quest":		WHT"Ôíµ×òþÑ¥"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([	"quest":		HIC"²½ÔÆÑ¥"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([      "quest":                "Òø»¨Çàµ×Åû¼çÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([      "quest":                "½ð»¨»Æµ×·É»ËÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([	"quest":		RED"ÐÄ×ÖÂÞÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([	"quest":		HIG"ôä´äÈö»¨ÑóñÞÈ¹"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([      "quest":                HIR"ÇáºìÂÞÉ´"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            450,
        ]),
        ([	"quest":		MAG"ÐþÉ«½ôÉí¾¢×°"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([	"quest":		HIY"°Ùµû´©»¨¼ýÐäÅÛ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([	"quest":		YEL"ÇïÏã³¤ËëË¿ÌÐ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		450,
	]),
	([      "quest":                "Ò¶áç",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           85,
        ]),
        ([      "quest":                "Ò¶Óð",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           50,
        ]),
        ([      "quest":                "ËïÐãÇà",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ê¯ÐãÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÂíÐãÕæ",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ò¶ÐãÖé",
                "quest_type":           "É±",
                "exp_bonus":            350,
                "difficulty":           10,
        ]),
	([	"quest":		"½ð½äÖ¸",
		"quest_type":		"Ñ°",
                "exp_bonus":		400,
                "difficulty":           550,

	]),
	([	"quest":		"Òø½äÖ¸",
		"quest_type":		"Ñ°",
                "exp_bonus":		400,
                "difficulty":           550,

	]),
	([	"quest":		"ÌúÀ×",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"Ìú³©",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
        ([      "quest":                "ÌúÓê",
                "quest_type":           "É±",
                "exp_bonus":            550,
        ]),
        ([      "quest":                "ÌúÉ½",
                "quest_type":           "É±",
                "exp_bonus":            550,
        ]),
        ([      "quest":                "ÀÇÍ·µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            550,
        ]),
        ([      "quest":                "Ìú½­",
                "quest_type":           "É±",
                "exp_bonus":            550,
        ]),
        ([      "quest":                "Ìú·ç",
                "quest_type":           "É±",
                "exp_bonus":            550,
        ]),
	([	"quest":		MAG"×Ï´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		YEL"»Æ´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		RED"ºì´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),	
	([	"quest":		"¡¸Ì«¼«È­Æ×¡¹",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"ºÂÉúÒâ",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"ÌìÁú",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"ÌìÐû",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"Ìì·ï",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"ÁøÈýÀÉ",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"ÁøçÛÃÃ",
		"quest_type":		"É±",
		"exp_bonus":		550,
	]),
	([	"quest":		"Ç³ºì³ñÉÀ",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
	([	"quest":		"°×ÂÞÅÛ",
		"quest_type":		"Ñ°",
                "exp_bonus":		550,
	]),
        ([      "quest":                "ëÙËÉ",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Äá°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Îå»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "ÆÕÉú",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                HIW"°×ÂìÒÏ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "½ðÁéÖ¥",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
        ([      "quest":                "Ì½ÏÕÕß",
                "quest_type":           "É±",
                "exp_bonus":            580,
        ]),
	([	"quest":		HIY"³Èïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		GRN"ÂÌïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		CYN"Çàïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		BLU"À¶ïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		MAG"×Ïïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		YEL"»Æïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),
	([	"quest":		RED"ºìïí"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		580,
	]),		
// end 580k
        ([      "quest":                "½ðÊ¨×Ó",
                "quest_type":           "É±",
                "exp_bonus":            600,
        ]),
	([	"quest":		CYN"ÇàÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		600,
	]),
	([	"quest":		"Éòèµ¾ý",
		"quest_type":		"É±",
		"exp_bonus":		600,
	]),
	([	"quest":		"Àî´ó×ì",
		"quest_type":		"É±",
		"exp_bonus":		600,
	]),
        ([      "quest":                HIC"ÒøÂìÒÏ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            600,
        ]),      
	([	"quest":		"ÕÔÄÜ",
		"quest_type":		"É±",
		"exp_bonus":		600,
	]),
	([	"quest":		"À°Íè",
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		"½ð²»Î·",
		"quest_type":		"É±",
		"exp_bonus":		600,
	]),
	([	"quest":		"²Ë»¨ÉßÆ¤",
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		HIY"³ÈÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		GRN"ÂÌÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		CYN"ÇàÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		BLU"À¶ÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		MAG"×ÏÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		YEL"»ÆÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		RED"ºìÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),		
	([	"quest":		HIY"Çïº£ÌÄ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
	([	"quest":		HIW"èÙ×Ó»¨"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		600,
	]),
        ([      "quest":                "Ìú´«¼×",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "ÖÐÄêÎÄÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                "³Ö¹úÌìÍõ",
                "quest_type":           "É±",
                "exp_bonus":            630,
                "difficulty":           15,
        ]),
        ([      "quest":                "Àµß¸µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
        ]),
        ([      "quest":                HIR"¾Å»·´ó¿³µ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
        ]),
        ([      "quest":                HIY"Îå"+HIR"²Ê"NOR+"Ð¡¶µ¶Ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
        ]),
        ([	"quest":		"Å®ÍÁ·Ë",
		"quest_type":		"É±",
		"exp_bonus":		630,
	]),
        ([      "quest":                "Ð¡ÁÕ",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),     
        ([      "quest":                "ÀÏÆ¤",
                "quest_type":           "É±",
                "exp_bonus":            630,
        ]),
        ([      "quest":                HIG"³û¾Õ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            630,
                "difficulty":           40,
        ]),
	([	"quest":		"Áù´ü²¼ÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		HIY"³È½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		GRN"ÂÌ½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		CYN"Çà½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		BLU"À¶ÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		650,
	]),
	([	"quest":		BLU"À¶½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		MAG"×Ï½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		YEL"»Æ½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),
	([	"quest":		RED"ºì½í"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		650,
	]),		
	([	"quest":		"·çÉ§ÑÅÈË",
		"quest_type":		"É±",
		"exp_bonus":		650,
	]),
//end 630k
        ([      "quest":                "ËáÃ·ÌÀ",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),    
	([	"quest":		"ÍòÐ¡´º",
		"quest_type":		"É±",
		"exp_bonus":		680,
	]),
	([      "quest":                "·É±ª×Ó",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
	([	"quest":		GRN"´äÐä»¤ÐÄµ¤"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		680,
	]),
	([	"quest":		WHT"°×ÔÆÐÜµ¨Íè"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		680,
	]),
	([	"quest":		RED"¾Å»¨ÓñÂ¶Íè"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		680,
	]),
        ([      "quest":                "Ëº³ÉÌõµÄ²¼ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            680,
        ]),
        ([      "quest":                "Ì«°×ÒÝ",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
        ([      "quest":                "ÇàÁú»áµÜ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            680,
        ]),
	([	"quest":		"´ò¸üµÄ",
		"quest_type":		"É±",
		"exp_bonus":		700,
	]),
	([	"quest":		"¡¸ÎåÐÐÉí·¨Í¼¡¹",
		"quest_type":		"Ñ°",
		"exp_bonus":		700,
	]),
	([	"quest":		"¡¸Ì«¼«ÄÚ¹¦ÈëÃÅ¡¹",
		"quest_type":		"Ñ°",
		"exp_bonus":		700,
	]),
	([	"quest":		HIB"·çÐÅ×Ó"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		700,
	]),
	([	"quest":		HIC"°ÙºÏ»¨"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		700,
	]),
	([	"quest":		MAG"×ÏÒÂÉÙÅ®"NOR,
		"quest_type":		"É±",
                "exp_bonus":		700,
	]),
	([	"quest":		HIR"´óºì¼ª·þ"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		700,
	]),
	([	"quest":		"Ï²Äï",
		"quest_type":		"É±",
                "exp_bonus":		700,
	]),
	([	"quest":		"ÊáÍ·ÀÏÊ¦¸µ",
		"quest_type":		"É±",
                "exp_bonus":		700,
	]),
//end 680k
        ([      "quest":                "¼Ð¹÷",
                "quest_type":           "É±",
                "exp_bonus":            750,
        ]),       
	([	"quest":		"¹ãÄ¿ÌìÍõ",
		"quest_type":		"É±",
		"exp_bonus":		750,
	]),
	([	"quest":		"ÅþÉ³ÃÅËþ",
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"½ð¹âÃ÷¾­",
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"·¨¾ä",
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"Äàºã",
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"ÍõÏÀÆï",
		"quest_type":		"É±",
		"exp_bonus":		750,
	]),
	([	"quest":		CYN"Ö¯½õ¾¢×°"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		RED"×ÏÍ­»¤ÐÄ¾µ"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		CYN"È÷½ð¶·Åñ"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"¹¬×°ÃÀæ¾",
		"quest_type":		"É±",
		"exp_bonus":		750,
	]),
	([	"quest":		HIW"ËØÉ«¹¬×°"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
	([	"quest":		"³¤·¢ÉÙÅ®",
		"quest_type":		"É±",
		"exp_bonus":		750,
	]),
	([	"quest":		GRN"´äÉ«ÇáÉ´"+RED"ºìÂÞÈ¹"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		750,
	]),
//end 735k
        ([      "quest":                "½ð¸®ÃÅ·¿",
                "quest_type":           "É±",
                "exp_bonus":            790,
        ]),
	([      "quest":                "ÀîÒåÆï",
	        "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           25,
        ]),
        ([      "quest":                "°×·É·É",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           25,
        ]),
        ([      "quest":                HIW"°×É´"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        
        
        ([      "quest":                "·ïÍ·¸«",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "Àæ»¨Ç¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "Õº½ð´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "°Ù±Ù±¦µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "ÊìÍ­¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        
        ([      "quest":                "ÁúÈª±¦½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "»¢Î²±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        
        
        
        ([      "quest":                "±í¸ç",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           25,
        ]),
        ([      "quest":                "ÎèÁø½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "¹ËÔÆ·ÉµÄÃØº¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
        ([      "quest":                "Ò¶¹Âºè",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           20,
        ]),
        ([      "quest":                "Õ¼²·ÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            790,
        ]),
/*        ([      "quest":                "ºúÌú»¨",
                "quest_type":           "É±",
                "exp_bonus":            790,
                "difficulty":           20,
        ]),*/
	([	"quest":		"Ó¥ÑÛÀÏÆß",
		"quest_type":		"É±",
		"exp_bonus":		800,
	]),
/*	([	"quest":		RED"Ð±ÑôÒÐ´äºìÐäÕÐ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		5000,
                "difficulty":           100,

	]),*/
	([	"quest":		"ÕÅÈý",
		"quest_type":		"É±",
		"exp_bonus":		800,
	]),
	([	"quest":		HIC"ÇàÍ·ÅÁ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		HIR"ºìÑü´ø"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		"Ëï³ÛÆï",
		"quest_type":		"É±",
		"exp_bonus":		800,
	]),
	([	"quest":		"ÕÔÒ»µ¶",
		"quest_type":		"É±",
		"exp_bonus":		800,
	]),
	([	"quest":		HIC"Çà²¼¼ýÒÂ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		HIY"½ð±³´ó¿³µ¶"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		"ÃçÉÕÌì",
		"quest_type":		"É±",
		"exp_bonus":		800,
	]),
	([	"quest":		"³¤±úÃçµ¶",
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		RED"×ÏºìÅÛ"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		WHT"°×É«Åû·ç"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		"´Ö²¼ÂéÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
	([	"quest":		"´óÊ¯´¸",
		"quest_type":		"Ñ°",
                "exp_bonus":		800,
	]),
//exp 800k
	([	"quest":		"Ðå»¨Ð¡Ð¬",
		"quest_type":		"Ñ°",
                "exp_bonus":		845,
	]),
        ([      "quest":                "ÎÞÃû·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "Öî¸ðÐ¡À×",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "ÍõïÚÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "·¨»ª¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "·¨º£²Ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "ÖìÆßÆß",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "·½ÐÄÆï",
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                RED"Ñªòùòð"NOR,
                "quest_type":           "É±",
                "exp_bonus":            845,
        ]),
        ([      "quest":                "ÂäÆÇÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            845,
                "difficulty":           25,
        ]),
//end 845k
	([	"quest":		HIC"ÇàÒíòùòð"NOR,
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"¼ÞÒÂÉñ¹¦",
		"quest_type":		"Ñ°",
                "exp_bonus":		900,
	]),
	([	"quest":		"ÄÏ¹¬Ê®Ò»ÀÉ",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"ÂÌÖé",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"ÀäÑª´Ì¿Í",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"ÇàÒÂ·þ",
		"quest_type":		"Ñ°",
                "exp_bonus":		900,
	]),
	([	"quest":		HIG"ÇàÒÂ´Ì"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		900,
	]),
	([	"quest":		"ÑªÑÀ",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"ÑªÍ·ÍÓ",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
	([	"quest":		"ÍÕ±³ÀÏÈË",
		"quest_type":		"É±",
		"exp_bonus":		900,
	]),
        ([      "quest":                "°×»·",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
	([      "quest":                "ÄÚ¹¦ÐÄ·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "µûÁµ»¨½£·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "°×Ý¦",
                "quest_type":           "É±",
                "exp_bonus":            900,
        ]),
        ([      "quest":                "¸ßÑÇÄÐ",
                "quest_type":           "É±",
                "exp_bonus":            900
        ]),
        ([      "quest":                "¶¡·ã",
                "quest_type":           "É±",
                "exp_bonus":            900
        ]),
        ([      "quest":                "ËïÔ¶³¬",
                "quest_type":           "É±",
                "exp_bonus":            900
        ]),
        ([      "quest":                "ºì×ìÎÚÑ»",
                "quest_type":           "É±",
                "exp_bonus":            900
        ]),
//end 900
	([      "quest":                "Æß²Êòùòð",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           12,
        ]),
        ([      "quest":                "Çå·çÊ®ÈýÊ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
                "difficulty":           12,
        ]),
        ([      "quest":                "ÎºÐÐÁú",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           12,
        ]),
        ([      "quest":                HIR"ÏÊºìÒÂÉÑ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÀîºìÐä",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           20,
        ]),
        ([      "quest":                "Ôö³¤ÌìÍõ",
                "quest_type":           "É±",
                "exp_bonus":            955,
                "difficulty":           15,
        ]),
        ([      "quest":                "²©²æ³àË÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            955,
        ]),
        ([      "quest":                "ÑªÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            955,
        ]),
        ([      "quest":                "·ïÆÜÎà",
                "quest_type":           "É±",
                "exp_bonus":            955,
        ]),
	([	"quest":		"Ð¡Ê¯×Ó",
		"quest_type":		"Ñ°",
                "exp_bonus":		1000,
	]),
	([	"quest":		"ÍõÒ»»¢",
		"quest_type":		"É±",
		"exp_bonus":		1000,
	]),
	([	"quest":		HIC"¿ªÉ½¸«"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		1000,
	]),
	([	"quest":		"ÄÏ¹¬Ê®¶þÀÉ",
		"quest_type":		"É±",
		"exp_bonus":		1000,
	]),
	([	"quest":		"À¶À¼",
		"quest_type":		"É±",
		"exp_bonus":		1000,
	]),
	([      "quest":                "¶Ì¸èµ¶·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1000,
        ]),
        ([      "quest":                "Ò»¼ôÃ·»¨ÊÖÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1000,
        ]),
	([	"quest":		HIB"À¶É«³¤È¹"NOR,
		"quest_type":		"Ñ°",
                "exp_bonus":		1000,
	]),
//end 955
	([	"quest":		"¿¾ÈéÖí",
		"quest_type":		"Ñ°",
                "exp_bonus":		1010,
	]),
	([	"quest":		"ÑªÑÀ",
		"quest_type":		"É±",
		"exp_bonus":		1010,
	]),
	([	"quest":		"ÄÏ¹¬Ê®¶þÀÉ",
		"quest_type":		"É±",
		"exp_bonus":		1010,
	]),
	([	"quest":		"À¶À¼",
		"quest_type":		"É±",
		"exp_bonus":		1010,
	]),
	([      "quest":                "¶Ì¸èµ¶·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
                "difficulty":           35,
        ]),
	([      "quest":                "ÊÌÎÀÍ³Áì",
                "quest_type":           "É±",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                RED"µÎÑªµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                "ÌúºÐ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
                "difficulty":           35,   
      	]),          
        ([	"quest":		"½£¶ù",
		"quest_type":		"É±",
		"exp_bonus":		1010,
        ]),
        ([      "quest":                "Ñ©ÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                "·çÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                "ÔÆÉÑ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                "Ï¸Ï¸µÄµöÓã¸Í",
                "quest_type":           "Ñ°",
                "exp_bonus":            1010,
        ]),
        ([      "quest":                HIY"½ð´óË§"NOR,
                "quest_type":           "É±",
                "exp_bonus":            1010,
        ]),
//end 1010

	([      "quest":                "Óù³ø",
                "quest_type":           "É±",
                "exp_bonus":            1065,
        ]),
        ([      "quest":                "¶¨°î´óÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            1065,
        ]),
        ([      "quest":                "³ð¶þÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            1065,
        ]),
        ([      "quest":                "ÒÒ³ÉÏÉ",
                "quest_type":           "É±",
                "exp_bonus":            1065,
        ]),
        ([      "quest":                "·ð¹âìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1065,
        ]),
	([	"quest":		"ÉÌÓñÁú",
		"quest_type":		"É±",
		"exp_bonus":		1100,
	]),
	([	"quest":		"Ìú¹³",
		"quest_type":		"Ñ°",
                "exp_bonus":		1100,
	]),
	([      "quest":                "Çï·ç²½·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1100,
        ]),
        ([      "quest":                "ÆåµÀÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1100,
        ]),
	([	"quest":		"ÊØ»¤ÌìÍõ",
		"quest_type":		"É±",
		"exp_bonus":		1100,
	]),
	([	"quest":		"ÇàÉ«±¦½£",
		"quest_type":		"Ñ°",
                "exp_bonus":		1100,
	]),
        ([      "quest":                "¾ÆÈâºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            1100,
        ]),
//end 1065
        ([      "quest":                "ÓÍ¹¸°ß°ßµÄÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "×Ï°ß¾Þòþ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "°×¾±»ÒÐÜ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "°×¶îÃÍ»¢",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÈËºÍÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÌúÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÔÆËÉ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ëÙºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "Æß»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "³àËÉ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                HIW"±ùÊ¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "Ë®Í°°ã´ÖÏ¸µÄ´óº£òþ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "Ï´ÒÂÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
                ([      "quest":                "´ó¶Ç×ÓµÄÐ¡Ï±¸¾",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
                ([      "quest":                "Ï´ÒÂ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
                ([      "quest":                "´äÅ¨",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
                ([      "quest":                "ÌÕ±£Òå",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
                ([      "quest":                "ÌÕÊÏ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÕÔ´ó·½",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÀîÂí»¢",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "Âí·¼Áá",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "Ð¡»¢×Ó",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "ÖÐÄê»ï¼Æ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        ([      "quest":                "´ïÍÞ",
                "quest_type":           "É±",
                "exp_bonus":            1120,
        ]),
        
//end 1120
([	"quest":		BLK"ºÚë«ëª²ØÅÛ"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		1200,
	]),
        ([      "quest":                "Ð¡Äá¹Ã",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "ÖñÒ¶Éß",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "ÇàÖñÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "²Øéá",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "´ïÍÞ",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        
        ([      "quest":                "º®Ã·ÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "¹ÂËÉÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "ºÚÃæÀÇ",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "ºÚÑÛÀÇ",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
        ([      "quest":                "ÌúÕ½",
                "quest_type":           "É±",
                "exp_bonus":            1175,
        ]),
	([	"quest":		"»î·ð",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		"ÍêÑÕ¸Ö",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		"ÍêÑÕÌú",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		"Ò¶¹¬",
		"quest_type":		"É±",
		"exp_bonus":		2400,
	]),
	([	"quest":		"ºÚÐÄÀÇ",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		"ÀÇÑÀ°ô",
		"quest_type":		"Ñ°",
		"exp_bonus":		1200,
	]),
	
	([	"quest":		"½­×óË¾Í½",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		"º«Áæ",
		"quest_type":		"É±",
		"exp_bonus":		1200,
	]),
	([	"quest":		HIW"ºüÆ¤°À"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		1200,
	]),
//end 1175
        ([      "quest":                "°×ÒÂ×³ºº",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "´óÄ®ÉÌÂÃ",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "Âí»Ø»Ø",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "Ö±¹²ËÂµÄÀ®Âï",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "°öÆÕËÂµÄÀ®Âï",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "ØñÙÍÀÏÍ·",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "ÂíÊ®",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        
        



        ([      "quest":                "ÒøÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "µØÀûÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                GRN"´äÖñÀº"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                "ºìÄï×Ó",
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
        ([      "quest":                RED"½ðè´ºì°À"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1230,
        ]),
	([	"quest":		"ÕË·¿ÏÈÉú",
		"quest_type":		"É±",
		"exp_bonus":		1230,
	]),
	([	"quest":		"Áø½ðÁ«",
		"quest_type":		"É±",
		"exp_bonus":		1230,
	]),
	([	"quest":		HIR"´óºì¶ÐÈ¹"NOR,
		"quest_type":		"Ñ°",
		"exp_bonus":		1230,
	]),
        ([      "quest":                HIY"½ðÂìÒÏ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            1230,
        ]),
//end 1230
        ([      "quest":                "»¢Í·Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            1290,
        ]),
        ([      "quest":                "Ð¡¶Ì¿ã",
                "quest_type":           "Ñ°",
                "exp_bonus":            1290,
        ]),
        ([      "quest":                "À÷Çà·æ",
                "quest_type":           "É±",
                "exp_bonus":            1290,
        ]),
        ([      "quest":                "ÒøÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            1290,
        ]),
        ([      "quest":                "Äª²»Çü",
                "quest_type":           "É±",
                "exp_bonus":            1290,
        ]),
        ([      "quest":                "ºÚÉ´ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1290,
        ]),
	([	"quest":		"Æß´ü²¼ÒÂ",
		"quest_type":		"Ñ°",
                "exp_bonus":		1290,
	]),
	([      "quest":                "½ðÎÞÍû",
                "quest_type":           "É±",
                "exp_bonus":            1290,
        ]),
	([	"quest":		"ÓñÊÖïí",
		"quest_type":		"Ñ°",
                "exp_bonus":		1290,
	]),
//end 1290
        ([	"quest":		"Óñ²±Ì×",
		"quest_type":		"Ñ°",
                "exp_bonus":		1350,
	]),
        ([      "quest":                "½ðÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1350,
        ]),
        ([      "quest":                "ÌìÊ±ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            1350,
        ]),
        ([      "quest":                "×¿ÈýÄï",
                "quest_type":           "É±",
                "exp_bonus":            1350,
        ]),
        ([      "quest":                "Ó¥×¦ÃÅÃÅ¹æ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1350,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÍõÌìÊÙ",
                "quest_type":           "É±",
                "exp_bonus":            1350,
                "difficulty":           20,
        ]),
        ([      "quest":                "´ßÃü·û",
                "quest_type":           "É±",
                "exp_bonus":            1350,
        ]),
        ([      "quest":                HIR"ÓÎ»êË÷"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1350,
        ]),
        ([		"quest":		HIR"´óºì¶ÐÈ¹"NOR,
				"quest_type":		"Ñ°",
				"exp_bonus":		1350,
		]),
        ([      "quest":                HIY"½ðÂìÒÏ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            1350,
        ]),
        ([      "quest":                "¹ÂËÉÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            1350, 
		]),
//end 1350
        ([      "quest":                "ÀÏÕÅ",
                "quest_type":           "É±",
                "exp_bonus":            1400,
		]),
        ([		"quest":		"ÕÅ¶÷",
				"quest_type":		"É±",
				"exp_bonus":		1400,
		]),
		([      "quest":                "¿Õ¹â",
                "quest_type":           "É±",
                "exp_bonus":            1400,
                "difficulty":           15,
        ]),
        ([      "quest":                "·¹²§",
                "quest_type":           "Ñ°",
                "exp_bonus":            1400,
        ]),
		([      "quest":                "ÌúÕÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1400,
        ]),
        ([      "quest":                "ºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            1400,
                "difficulty":           15,
        ]),
        ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            1400,
        ]),
//end 1410
	([	"quest":		"Ð¡¹«×Ó",
		"quest_type":		"É±",
		"exp_bonus":		1470,
	]),
	([	"quest":		"ÁÖÏÉ¶ù",
		"quest_type":		"É±",
		"exp_bonus":		1470,
	]),
	([	"quest":		"ÒøºìÉ¢»¨È¹",
		"quest_type":		"Ñ°",
                "exp_bonus":		1470,
	]),
        ([      "quest":                "Ñ²ÂßÊÌÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            1470,
                "difficulty":           20,
        ]),
        ([      "quest":                "òùòðµºµÜ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            1470,
                "difficulty":           20,
        ]),
        ([      "quest":                RED"µÎÑªµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1470,
        ]),
        ([      "quest":                "ÇÕÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            1470,  
        ]),
        ([      "quest":                "½äµ¶",  
                "quest_type":           "Ñ°",
                "exp_bonus":            1470,  
        ]),
	([	"quest":		"ÃæÄ¿¿Õ°×µÄÄ¾Ïñ",
		"quest_type":		"Ñ°",
                "exp_bonus":		1500,
	]),
	([	"quest":		"´óºÚÊ¯",
		"quest_type":		"Ñ°",
                "exp_bonus":		1500,
	]),
//end 1500
});

//Find the First Index to have exp level >= x
int Find(int x)
{
	int total;
	int low,high,now;
	total=sizeof(quest);

	if(quest[0]["exp_bonus"]>=x)
		return 0;
	if(quest[total-1]["exp_bonus"]<x)
		return total-1;

	low=0;
	high=total-1;
	now=(low+high)/2;

	while(high-low>1) {
		if(quest[now]["exp_bonus"]>=x)
			high=now;
		else 
   			low=now;
		now=(low+high)/2;
	}
	return high;
}

mapping query_quest(int exp)
{
	int a,b,c; 
	int low,high;

	if(exp>1000) {
		low=exp-200; 
		high=exp+600;
	}
	else {
		low=exp*8/10;
		high=exp*16/10;
	}

	if(low>5000) low=5000;  

	if(high<3) high=3;

	a=Find(low);
	b=Find(high)-1;
	c=a+random(b+1-a);
	return quest[c];
}

int TotalNumber()
{
	return sizeof(quest);
}

int KillNumber()
{
	int count=0;
	int i,total;
	total=sizeof(quest);
	for(i=0;i<total;i++) {
		if (quest[i]["quest_type"]=="É±") count++;
	}
	return count;
}        
