#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÎÞÁÄÉÙÄê",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÀÏ²Ã·ì",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÂôÒ©µÄ",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ºúÓ¢",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÍÁæ½",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Ñ¼ÓÍ°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Ð¡·ç³µ",
           "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÑòÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÄÚ¹¦ÐÄ·¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "¡¸¾Åèº¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),         ([      "quest":                CYN"´óÇà²Ë"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                WHT"Ð¡°×²Ë"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Ö½Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "°ü×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "¿¾¼¦ÍÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "¿¾ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
       ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "ÀÏÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "Ð¡µ£··",
                "quest_type":           "É±",
                "exp_bonus":            2, 
        ]),
        ([      "quest":                GRN"»Æ¹Ï"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2,
        ]),
// end 2k
        ([      "quest":                "ÀîÏ¼",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "×íºº",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Ò©µêÐ¡»ï¼Æ",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "°¢·¢",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "´ó±è×Ó¹ÃÄï",
                "quest_type":           "É±",
           "exp_bonus":            3,
        ]),
        ([      "quest":                "ÀÏ°åÄï",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "²è²©Ê¿",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "µ¥µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÄàÈË¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "´ó¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Ä§·¨¼ò½é",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "¡¸ËµÂÉ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÖíÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ÔÆÄÏ°×Ò©",
           "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Â±µ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Ø°Ê×",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "²¼´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "µ³²Î",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "Óñé¢×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "ºúÀÏÍ·",
                "quest_type":           "É±",
                "exp_bonus":            3,
        ]),
        ([      "quest":                "¿¾°ü×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
                "difficulty":           10,
        ]),
        ([      "quest":                "×¥·¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            3,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÆÏÌÑ¸É",
                "quest_type":           "Ñ°",
               "exp_bonus":                3,
                "difficulty":           10,
        ]),
//end 3k
        ([      "quest":                MAG"ÇáÂÞ³ñÉÀ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÕÅÌú½³",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÂôÍæ¾ßµÄ",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÁúÐ¡ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "¡¸Áº¸¸ÎÄ¼¯¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ËØ²Ë°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "»¢¹ÇÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Å£Í·",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Çá¹¦¼ò½é",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
   ]),
        ([      "quest":                "¡¸¼ÎµÂÎÄÑ¡¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Ö½»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "¡¸Ì«¹«±ç¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "·ûÖäÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "ÂòÓãµÄÐ¡¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            4,
        ]),
        ([      "quest":                "Ç§½ðÐ¡½ã",
                "quest_type":           "É±",
                "exp_bonus":            4,   
        ]),
//end 4k
        ([      "quest":                "Ð¡³´·ÛË¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "ÂäµÚÊéÉú",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "×¥ÆÆÃÀÈËÁ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "°¢²Ë¸ç",
           "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "´©¿ªñÉ¿ãµÄÐ¡º¢¶ù",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Ä¥²Ëµ¶µÄ",
                "quest_type":           "É±",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "è½×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "´óÃ×",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "²ÚÃæ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "±±ÜÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Ê¯Ê¨×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "´ó·çÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Éú¼å°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
   ([      "quest":                "ÅÙ»¨ÓÍ",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¡¸¹ÅÎÄÖ¾¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                RED"·¬ÇÑ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                MAG"ºúÂÜ²·"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "¡¸ÏçÊé¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                HIR"ëÙÖ¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",
                "exp_bonus":            5,
        ]),
//end 5k
        ([      "quest":                "Âô½äÖ¸µÄ",
                "quest_type":           "É±",
                "exp_bonus":            6,
                "difficulty":           10,
        ]),
        ([      "quest":                "Âô¿¾°ü×ÓµÄ",
           "quest_type":           "É±",
                "exp_bonus":            6,
                "difficulty":           10,
        ]),
        ([      "quest":                "Âô×¥·¹µÄ",
                "quest_type":           "É±",
                "exp_bonus":            6,
                "difficulty":           10,
        ]),
        ([      "quest":                "Âô¹þÃÜ¹ÏµÄ",
                "quest_type":           "É±",
                "exp_bonus":            6,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ñ©¸òó¡",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
                "difficulty":           10,
        ]),
        ([      "quest":                "´óÃÞ°À",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "ÀîÒ»Ãþ",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "×Ï²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "ºÚ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
   ([      "quest":                "ÃÞ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "À¶²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Ï´µÃ·¢°×µÄÉ®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Çà²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "°×²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "×Ï²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Çà²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "Ï´µÃ·¢°×µÄÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "ÃÞ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "´Ö²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
   ]),
        ([      "quest":                "ºÚ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
        ([      "quest":                "À¶²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            6,
        ]),
//end 6k
        ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "ÂÌÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "»Ò²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "âã»ÚÍ½",
                "quest_type":           "É±",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "ÑÅ·¼",
                "quest_type":           "É±",  
                "exp_bonus":            7,     
        ]),
        ([      "quest":                "Íõ»¢",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "Áø·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "Ïã¿Í",
                "quest_type":           "É±",  
                "exp_bonus":            7,     
        ]),
        ([      "quest":                "Ô¬¼§",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "Å©¼ÒÅ®",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "¾Â²ËºÏ×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "Ê¯Å£",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "´óó¯òë",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "Ð¡ó¯òë",
                "quest_type":           "É±",
                "exp_bonus":            7,
        ]),
        ([      "quest":                HIR"±»ÏÊÑª½þÍ¸µÄ²¼Ìõ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "»¨·Û´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "×ÓÄ¸Ë«»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
   ([      "quest":                "¹·Æ¤¸àÒ©",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "»¨Éú",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                YEL"Áú¾®²è"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
                "difficulty":           15,
        ]),
        ([      "quest":                "¼¦Èâ°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "ÌÒ·ûÖ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "ÓñÆÑÍÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "¡¸Ù«·çÕ«Ê«¼¯¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
        ([      "quest":                "¾Å½Ø±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            7,
        ]),
//end 7k
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",  
                "exp_bonus":            8,     
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "ÄêÇàÈË",
                "quest_type":           "É±",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "Áù½Ç´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "ÌôË®µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "Äî¾­µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "´òÔÓµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "É¨µØµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "¿³²ñµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "³¯°ÝµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "¸ßÈË",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),

        ([      "quest":                "ÂôÃæµÄÄêÇàÈË",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "ÉÕ·¹µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "ÌÔÃ×µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "°×É«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "ºÚÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "É¨°Ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "òÇò¾",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "Öñ·òÈË",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "É¥¾¡ÌìÁ¼µÄÐóÉú",
                "quest_type":           "É±",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "µÇÉ½Õß",
                "quest_type":           "É±",
                "exp_bonus":            8,

        ]),
        ([      "quest":                "Ê¯»ÒÊ¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "¹È×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            8,
        ]),
//end 8k
        ([      "quest":                "½õÄÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "Íü»ê»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                HIG"Íü»ê¹û"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÂôâÎµÄ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "Âô»¨Ã±µÄ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÂôÐ¡µ¶µÄ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),

        ([      "quest":                "Âô¿â³µ°×ÐÓµÄ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÂôÆÏÌÑ¸ÉµÄ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÁøÈôËÉ",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           15,
        ]),
        ([      "quest":                "´óÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "²É»¨æ¤",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "ÂãÌåÅ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            9,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÍõÈÊµÂ",
                "quest_type":           "É±",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
         ]),
        ([      "quest":                "Ð¡»Æ¹Ï",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "ËòÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "²è»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "±ÀÁË¿ÚµÄÐ¡µú¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÂÞ²·Ìõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "¡¸Ë®ÁúÍ¼×¢¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            9,
        ]),
//end 9k
        ([      "quest":                "Ð¡Áý°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ð¡µú¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),

        ([      "quest":                "ÓÍÓÍµÄÖ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¹È»Û¶ù",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å©¾ßµêÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "³ÁÏãÕòµÄµØÍ·Éß",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´óÀíÊ¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¼¦Ã«ë¦×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿³²ñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÐÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "²ÐÆÆ¹Å»­",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
                "difficulty":           10,
        ]),
        ([      "quest":                "À×»ðÖé",
                "quest_type":           "Ñ°",

                "exp_bonus":            10,
                "difficulty":           15,
        ]),
        ([      "quest":                "»¨½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
                "difficulty":           10,
        ]),
        ([      "quest":                "²ÊÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,   
        ]),
        ([      "quest":                "²ÉÁâÅ®",
                "quest_type":           "É±",
                "exp_bonus":            10,
                "difficulty":           10,
        ]),
        ([      "quest":                "»¨¹Ã",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÃåÓñ»¡",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÑîÀÏÌ«",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»î°þÆ¤",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿üÔª¹Ý»ï¼Æ",
                "quest_type":           "É±",

                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÉÜÐËÅ®¶ùºì",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "½´Å£Èâ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]), 
//end 10k
        ([      "quest":                "Ó©»ð³æ",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           10,
        ]),
        ([      "quest":                "´óÑã",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           10,
        ]),
        ([      "quest":                "Èíºì",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           10,
        ]),
        ([      "quest":                "ÕÑºì",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           10,
        ]),
        ([      "quest":                "²õÒíÉ´ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÎðÍüÎÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
                "difficulty":           30,

        ]),
        ([      "quest":                "Ê¯ÁñÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "´øÑªÉ´ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÂíÀÏËÄ",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÆßÐÇ´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÇàÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÖñÒ¶Çà¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÈçÒâ¿ÍÕ»ÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "ÀÏÎÝÈË",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "¹Ø¶«´óºº",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Ñª³¦",

                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            11,
        ]),
       ([      "quest":                 "¹Â»ê",
                "quest_type":           "É±",
                "exp_bonus":            11,
                "difficulty":           10,
        ]),
        ([      "quest":                "½ðÆ¿Ã·",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
        ]),             
//end 11k
        ([      "quest":                "À¶ÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            12,
                "difficulty":           20,
        ]),
        ([      "quest":                "·¢»ÆµÄÖ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "ÇÙ¶ù",
                "quest_type":           "É±",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "²Ý±àÂìòÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "ÓÍÆ¤´ü",

                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                HIC"ÎÞÓ°ÉñÕë"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "»¤ÐÄ¾µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "ÌìÏãÐøÃüÂ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
                "difficulty":           15,
        ]),
        ([      "quest":                "Õ½»ê",
                "quest_type":           "É±",
                "exp_bonus":            12,
        ]),     
        ([      "quest":                "¼«ÀÖåÐÒ£É¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "»¯Ê¬·Û",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "Ò¹ÐÐÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "¾«¸Ö·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "ºì×ìÐ¡ÂéÈ¸",
                "quest_type":           "É±",
                "exp_bonus":            12,

        ]),
        ([      "quest":                "ÎÚÀ­²´ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            12,
                "difficulty":           10, 
        ]),
        ([      "quest":                "Ó¢¼ªÉ³Ð¡µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "âÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "¡¸º®Ê¿ÁÐ´«¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            12,
        ]),        
//end 12k
        ([      "quest":                "òÐòÐ",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "ÃÛ·ä",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Ð¡±¦¶ù",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "½õÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Í­ÉÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
                "difficulty":           10, 

        ]),
        ([      "quest":                HIC"¹íÑÀÐþÚ¤ÕÈ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "±ùÐÄ¾÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "ÎäÁÖÐ¡ºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            13,  
        ]),
        ([      "quest":                "ÔÆÓÎÉ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Ó­¿ÍÉ®",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "×ÏÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            13,
                "difficulty":           20, 
        ]),
        ([      "quest":                "°ËÀãÐþÌú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Ë®ÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            13,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "exp_bonus":            13,
                "difficulty":           10, 

        ]),
        ([      "quest":                "ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            13,
                "difficulty":           10, 
        ]),
        ([      "quest":                "ÐíÁ®Áú",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "Åí³¤¾»",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "ËÎ³¤Çå",
                "quest_type":           "É±",
                "exp_bonus":            13,
        ]),
//end 13k
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "Çà·æ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "¸ßÁ»¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ÄÛÅº",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "²·ÑÇÄÐ",
                "quest_type":           "É±",
                "exp_bonus":            14,
                "difficulty":           10,

        ]),
        ([      "quest":                "À¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "Ñà¶ù",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ºúµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "²ØÏã",
                "quest_type":           "Ñ°",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "²è×©",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉßÒ©",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÓãÏß",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌÒ»¨Ö¦",
                "quest_type":           "Ñ°",

                "exp_bonus":            15,
                "difficulty":           10, 
        ]),
        ([      "quest":                "Ë®Éß",
                "quest_type":           "É±",
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "ÈËÓ°",
                "quest_type":           "É±",  
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "°×³ñ³¤Åû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),        
        ([      "quest":                "ÆÆ¾É²»¿°µÄ³¤ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ã×¾Æ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "÷ç½ÇÉ¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ë®¹ð",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ö£¼×",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÃåÓñïí",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),

//end 15k
        ([      "quest":                "¶ñÄ§Íö»ê",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "´Ð»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Ëó×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Ï¸ÂéÏß",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Ë®¾§Çò",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
                "difficulty":           15,
        ]),
        ([      "quest":                "»ðß¡×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ÐåÂúÁËÔª±¦µÄ³ñ´ó¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "º«ÕÆ¹ñ",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "¿¡ÇÎÏà¹«",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                HIC"Ïà¹«ÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "´ó³ø",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Â±Î¶¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ÑÅ¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ß¡ÉÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "ÇÎð±Ä¸",
                "quest_type":           "É±",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "Îèµû²ÊÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            16,
        ]),
//end 16k
        ([      "quest":                "Ð¡¹³×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÌÙÂÜÉþ",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,

        ]),
        ([      "quest":                "ÌÒ»¨°ê",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "Ðå»¨Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "Ä¢¹½",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",    
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ð¡´ä",
                "quest_type":           "É±",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",  
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "·ÛºìÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "Ï¸Ã·½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÄÁÑòÅ®",
                "quest_type":           "É±",

                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "ÑòÃ«È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "´óÏä×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            18,
        ]),
//end 18k
        ([      "quest":                WHT"±´¿Ç"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×Ã«½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÅÖÀÏÍ·",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»¤ËÂ²ØÄá",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Òõ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
                "difficulty":           15, 
        ]),
        ([      "quest":                "Ò»»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,

        ]),
        ([      "quest":                "´óºìÄáÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¹Å³ÇÉÕ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÍõÊ¯½³",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¼ÖÔ±ÍâµÄÅ®¶ù",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÔÆÄ¸·Û",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
//end 20k
        ([      "quest":                CYN"±ªÑÀÊÖ»·"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "ÊÝÂí",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "¶Ï³¦ÈË",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "¼ÒÅ«",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "¼ÒÅ«¶Ì¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "´óÀÏÊó",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "ÈËÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "¿¾É½ÖíÈâ",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "Óã¹ÇÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "À¯Öò",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "²Ëµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "´ÐÓÍ±ý",
                "quest_type":           "Ñ°",
                "exp_bonus":            23,
        ]),
       ([       "quest":                "Ð¡Óæ",
                "quest_type":           "É±",
                "exp_bonus":            23,  
        ]),              
       ([       "quest":                "½ð»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            23,  
        ]),

        ([      "quest":                "É³ÂÞÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "Ð¡°×ÍÃ",
                "quest_type":           "É±",
                "exp_bonus":            23,  
        ]),
        ([      "quest":                "ºûµû",
                "quest_type":           "É±",
                "exp_bonus":            23,
        ]),
//end 23k
        ([      "quest":                RED"Éºº÷"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                YEL"º£ÂÝ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),  
        ([      "quest":                "»¢ÎÆÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
                "difficulty":           20, 
        ]),
        ([      "quest":                "Óæ·ò",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                HIW"ÂíÃæ"NOR,
                "quest_type":           "É±",
                "exp_bonus":            25,
                "difficulty":           25, 

        ]),
        ([      "quest":                HIW"Å£Í·"NOR,
                "quest_type":           "É±",
                "exp_bonus":            25,
                "difficulty":           25, 
        ]),
        ([      "quest":                HIR"ÌúË÷"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                HIR"¼Ïîí"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¼§ÁéÑà",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Â½Îå´¨",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¼ÖÔ±Íâ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ºÚÉ«×¯·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "·çóÝ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
//end 25k
        ([      "quest":                MAG"Ð¡ó¦Ð·"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),

        ([      "quest":                WHT"±´¿Ç"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "±®ÎÄÍØ±¾",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "½­ºþÖÐÈË",
                "quest_type":           "É±",
                "exp_bonus":            28,
                "difficulty":           10, 
        ]),
        ([      "quest":                "´¬½°",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "Ãçµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "ÐÅ¸ë",
                "quest_type":           "É±",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "Ð¡Çà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "Ã·Ê÷Ó×Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "Ìú¸ä",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
        ]),
        ([      "quest":                RED"Éºº÷"NOR,
                "quest_type":           "Ñ°",

                "exp_bonus":            28,
        ]), 
        ([      "quest":                "ºúÉú",
                "quest_type":           "É±",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "¿¦°ÍÉ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            28,
                "difficulty":           35, 
        ]), 
        ([      "quest":                "µÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            28,
        ]),
//end 28k
        ([      "quest":                BLU"º£ÐÇ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            31,
        ]), 
       ([      "quest":                "ÍõÓ¨",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ÑàÉº",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ºìÉÕÅ£Èâ",
                "quest_type":           "Ñ°",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "×ÏÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            31,
        ]),        
        ([      "quest":                "ÃÉ¹ÅÈË",
                "quest_type":           "É±",
                "exp_bonus":            31,

        ]),
        ([      "quest":                "²»µ¤ÈË",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "ººÈË",
                "quest_type":           "É±",
                "exp_bonus":            31,
        ]),
        ([      "quest":                BLK"ºÚÓô½ðÏã"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            31,
                "difficulty":           25,
        ]),
//end 31k        
        ([      "quest":                "ºþÉÏ¾Æ",
                "quest_type":           "É±",
                "exp_bonus":            34,
                "difficulty":           10, 
        ]),
        ([      "quest":                "¾ÆÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "Ô°¹¤¼ô",
                "quest_type":           "Ñ°",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "Ð¡Ô°¹¤",
                "quest_type":           "É±",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "Å®Ó¶ÈË",
                "quest_type":           "É±",
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "¼¦Ã«",
                "quest_type":           "Ñ°",  
                "exp_bonus":            34,   

        ]),
        ([      "quest":                "Ð¡°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "°ë¸ÉµÄÄ¾²ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "Ð¡Î÷ÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "Ð¡¶µ¶µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            34,
        ]),
//end 34k
        ([      "quest":                "Ð¡Ãæ¹ÝµÄµØÆõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "¿ªñÉ¿ã",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "·çÇå",
                "quest_type":           "É±",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "´óÇà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "Ðå×ÅÃ·»¨µÄÔ¡½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "°×ÓñÐ¡ÂíÍ°",

                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "´ó°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "¸ÉÄ¾²ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "Ã·Ä¾³¤µÊ",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "Â·±ßµÄÒ°»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            36,
        ]),
        ([      "quest":                "½·ÑÎÃæ½î",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "ò»Î¶ÓãÃ×",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "¶Û½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "»¤Ôº",
                "quest_type":           "É±",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "Ð¡¶Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            37,
        ]),

        ([      "quest":                "³ø×Ó",
                "quest_type":           "É±",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "ÎðÍüÎÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            11,
                "difficulty":           30,
        ]),
//end 37k
        ([      "quest":                "±ÌÓñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Íã¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "¿Ý»ÆµÄÒ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Çà¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "¾Â²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                WHT"±´¿Ç"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "»¤ËÂÀ®Âï",
                "quest_type":           "É±",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "´óºìÉ®ÅÛ",

                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Ñô¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
                "difficulty":           20, 
        ]),
        ([      "quest":                "ÉÕ¼¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "´óÂøÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),        
        ([      "quest":                "Ð¡ÔÆÈ¸",
                "quest_type":           "É±",
                "exp_bonus":            41,
        ]),
        ([      "quest":                HIW"¹þ´ï"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "ÂéÉþ",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "°ë¸ÉµÄÑªµÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "Âí××Ä¾Ë¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "ÂÌ¶¹Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            41,

        ]),
//end 41k
        ([      "quest":                "ÐÂ½®µØÌº",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
                "difficulty":           10, 
        ]),
        ([      "quest":                "×°ÂíÄÌ×ÓµÄÆ¤´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
                "difficulty":           10, 
        ]),
        ([      "quest":                "¿â³µ°×ÐÓ",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
                "difficulty":           10, 
        ]),
        ([      "quest":                "Ò°ÈË²Î",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÐÜÕÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Â¹È×",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀËÓÎÊ«ÈË",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                BLU"º£ÐÇ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "Ñ©ÌãëÙÖ¬Âí",
                "quest_type":           "É±",

                "exp_bonus":            46,
        ]),
        ([      "quest":                "Å£Æ¤Âí°°",
                "quest_type":           "Ñ°",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "ÎÄÈËÄ«¿Í",
                "quest_type":           "É±",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "·çÁè",
                "quest_type":           "É±",
                "exp_bonus":            46,
                "difficulty":           20,
        ]),
//end 46k
        ([      "quest":                RED"Éºº÷"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¶¾Éß",
                "quest_type":           "É±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¿¼Éú",
                "quest_type":           "É±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ð¡½ð±­",
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
                "difficulty":           10, 
        ]),
        ([      "quest":                "¸ßÁ»¾Æ",
                "quest_type":           "Ñ°",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "µ¥ÉíÌË×ÓÊÖ",
                "quest_type":           "É±",

                "exp_bonus":            51,
        ]),
        ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "»õÆ±",
                "quest_type":           "Ñ°",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "·®·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            51,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÂÞ´ï³É",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ËÕÂê",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "ÂíÂ³",
                "quest_type":           "É±",
                "exp_bonus":            51,
        ]),
//end 51k
        ([      "quest":                "¹ÅÐÎ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "¹Â¶ÀÃÀ",
                "quest_type":           "É±",
                "exp_bonus":            55,
                "difficulty":           15, 
        ]),
        ([      "quest":                HIR"É±ÊÖ½£"NOR,
                "quest_type":           "Ñ°",

                "exp_bonus":            55,
        ]),
        ([      "quest":                HIR"É±ÊÖÈÐ"NOR,
                "quest_type":           "Ñ°",

                "exp_bonus":            55,
        ]),
        ([      "quest":                "É±ÊÖÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÀäÇï»ê",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÊÝæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÅÖæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÍÂÂ³·¬ÉÙÅ®",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Òø»¤ÎÀ",
                "quest_type":           "É±",  
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ºÚÉ«½Ì·þ",
                "quest_type":           "Ñ°",  
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "ÍõÈô¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            55,
                "difficulty":           10,   
        ]),
        ([      "quest":                "ÕÅËÆ¸Ö",
                "quest_type":           "É±", 
                "exp_bonus":            55, 
                "difficulty":           10,  

        ]),
        ([      "quest":                "»ÆÉ«½Ì·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,  
        ]),
        ([      "quest":                "Óñ°¼×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
//end 55k
        ([      "quest":                "·ç¾²",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÌïÐÄ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "³¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "»ÆÒÂÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "½ðÇ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ºÚ¹·",

                "quest_type":           "É±",
                "exp_bonus":            60,
                "difficulty":           25,
        ]),
        ([      "quest":                HIY"Îå"+HIR"²Ê"NOR+"½ôÉíÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "·çÔÆÂí¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÌïÅòÀÉ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
//end 60k
        ([      "quest":                "öùÓã",
                "quest_type":           "É±",
                "exp_bonus":            65,
                "difficulty":           25,
        ]),
        ([      "quest":                "¹ùáÔÑô",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ÏìÎ²Éß",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "´óºº",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "Ê÷Ö¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ÀîÈü¸Ö",

                "quest_type":           "É±",
                "exp_bonus":            65,  
                "difficulty":           10, 
        ]),
        ([      "quest":                "ÕÔÈç¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            65,
                "difficulty":           10, 
        ]),
        ([      "quest":                "³ÇÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            65,
                "difficulty":           10, 
        ]),
        ([      "quest":                "ËþÉ®",
                "quest_type":           "É±",
                "exp_bonus":            65,
                "difficulty":           10, 
        ]),
        ([      "quest":                "Èý»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ºþÉÏ²Ý",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "²ÝÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "ºþÉÏ»¨",
                "quest_type":           "É±",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "»¨ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),

//end 65k
        ([      "quest":                "¹þÃÜ¹Ï",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "¿¨ÄãÍßÒÀÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Å£Æ¤´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "×°ËáÄÌ×ÓµÄÆ¤´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Ë®Áé¹â",
                "quest_type":           "É±",
                "exp_bonus":            71,
                "difficulty":           35,
        ]),
        ([      "quest":                "ºþÉÏÅ®",
                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Å®ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "ºþÉÏË®",
                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Ë®ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "ºþÉÏÑ©",

                "quest_type":           "É±",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "Ñ©ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            71,
        ]),
//end 71k
        ([      "quest":                "µ±¹é",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "½£ÄÏ´º¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "ÃæÌõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "Â«Î­",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
        ([      "quest":                HIR"¶Ï³¦²Ý"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
                "difficulty":           10, 
        ]),
        ([      "quest":                "ºÚÓñ·¢ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            78,
        ]),
        ([      "quest":                "Á¼¼Ò¸¾Å®",
                "quest_type":           "É±",
                "exp_bonus":            78,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÀÏºüÀê",

                "quest_type":           "É±",
                "exp_bonus":            78,
                "difficulty":           15, 
        ]),
        ([      "quest":                "ÀîÕÆ¹ñ",
                "quest_type":           "É±",
                "exp_bonus":            78,
        ]),
        ([      "quest":                GRN"Á«Åî"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":                HIC"À¶É«°ÙñÞÈ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":                "Çå³´ÏºÈÊ",
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
        ([      "quest":                "¸¬Ñ©»ÆÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            80,
        ]),
//end 80k
        ([      "quest":                "³ÂÆ¤´óÏº",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "¹ûÖ­ÓãÇò",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "ËÕÈØÈØ",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ð»³¤ÇÚ",
                "quest_type":           "É±",

                "exp_bonus":            85,
        ]),
        ([      "quest":                "Àî³¤É÷",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "¹©Ïã",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Óü×ä",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "Ð¡ÌÒºì",
                "quest_type":           "É±",
                "exp_bonus":            85,
        ]),        
        ([      "quest":                "·Ûºì°À",
                "quest_type":           "Ñ°",
                "exp_bonus":            85,
        ]),
//end 85k
        ([      "quest":                "ÎäÁÖ´óºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            89,
                "difficulty":           15,
        ]),
        ([      "quest":                "Ìú»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,

        ]),
        ([      "quest":                "Í­»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "½ð·ç",
                "quest_type":           "É±",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "½ðÓê",
                "quest_type":           "É±",
                "exp_bonus":            89, 
        ]),
        ([      "quest":                "Ò»¾ß¿ÝÇ¬µÄº¡¹Ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            89,
        ]),
//end 89k
        ([      "quest":                "Ð¡Ï²Èµ",
                "quest_type":           "É±",
                "exp_bonus":            93,
        ]), 
        ([      "quest":                BLK"ºÚÓô½ðÏã"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
                "difficulty":           35,
        ]),
        ([      "quest":                "ºÚ¹Ú¾Þòþ",
                "quest_type":           "É±",
                "exp_bonus":            93,
                "difficulty":           15,
        ]),
        ([      "quest":                "Öª¿ÍµÀÈË",
                "quest_type":           "É±",
                "exp_bonus":            93,

                "difficulty":           15,
        ]),
        ([      "quest":                "»ÆÉ«µÀ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "Çà²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "½ð½­",
                "quest_type":           "É±",
                "exp_bonus":            100,
                "difficulty":           15, 
        ]), 
        ([      "quest":                "½ðÉ½",
                "quest_type":           "É±",
                "exp_bonus":            100,
                "difficulty":           15, 
        ]),  
        ([      "quest":                "ÀÏºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "°×ÃÞôÂôÄ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÄÏ¹¬Ê®ÈýÀÉ",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "°ÙÀïÁé",   
              "quest_type":           "É±",
                "exp_bonus":            100,

        ]),
        ([      "quest":                "ËÎÖÐ",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
// end 100k
        ([      "quest":                "ÖóÊìÁËµÄÇù",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "exp_bonus":            105,
                "difficulty":           15,
        ]),
        ([      "quest":                "Íäµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "´óºì²¼ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "»¤É½Ê¹Õß",
                "quest_type":           "É±",
                "exp_bonus":            105,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "´óºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "¾«ÖÂÄñÁý",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,

        ]),
        ([      "quest":                "ÈéÏãöðÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            105,
        ]),
//end 105k
        ([      "quest":                "¹³Á¬Ç¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                BLK"ºÚÓô½ðÏã"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
                "difficulty":           30,
        ]),
        ([      "quest":                "¹ÅËÉÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
                "difficulty":           10, 
        ]),
        ([      "quest":                "Àî±ª",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "ïÚÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "Ê¯Ëø",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                WHT"»ÆÉ½·ç¾°Í¼"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            110,

        ]),
        ([      "quest":                "½ðË¿È¸",
                "quest_type":           "É±",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "Çå³´ÏºÈÊ",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "°×Öó¼¦µ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            110,
        ]),
//end 110k
        ([      "quest":                "´äÓñÅýÅÃ",
                "quest_type":           "Ñ°",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "°¢¸£",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "¾ÞÐÍÈ®",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "ÁõÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "»ôÓ¢",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "¶ÅÒ÷",
                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "°¢ÒÀ¹ÅÀö",

                "quest_type":           "É±",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "×Ï½ðºùÂ«",
                "quest_type":           "Ñ°",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "°¬ÈÞ",
                "quest_type":           "Ñ°",
                "exp_bonus":            120,
                "difficulty":           20,
        ]),
        ([      "quest":                RED"Ò°¹û"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            120,
        ]),
//end 120k
        ([      "quest":                "ÔÀÑó",
                "quest_type":           "É±",
                "exp_bonus":            130,
                "difficulty":           20,
        ]),
        ([      "quest":                "»¢¹Ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            130,
        ]),
        ([      "quest":                BLK"ºÚÑ¥"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            130,
        ]),
        ([      "quest":                BLK"ºÚÉ´"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            130,
        ]),
        ([      "quest":                "¾¢×°ÉÙÄê",
                "quest_type":           "É±",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "¹«Ëï²»ÖÇ",

                "quest_type":           "É±",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂÉÙÅ®",
                "quest_type":           "É±",
                "difficulty":           15,
                "exp_bonus":            132,
        ]),
        ([      "quest":                "Çà´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "ÇàÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "Âä»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            132,
        ]),        
// end 132k
        ([      "quest":                HIC"Æß"HIB"²Ê"HIG"º£"HIY"ÂÝ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            140,
                "difficulty":           15, 
        ]),
        ([      "quest":                "Îý»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "¶ÁÇ§Àï",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "ÀÏÊµºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                HIR"Æß"+HIY"²Ê"+HIG"Ë¿¶Ð´ø"NOR,

                "quest_type":           "Ñ°",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "·¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "´óºú×ÓºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "ºÚ´ÉÒ©ÎÍ",
                "quest_type":           "Ñ°",
                "exp_bonus":            150,
                "difficulty":           25, 
        ]),
        ([      "quest":                "Í­·ð¹Ä",
                "quest_type":           "Ñ°",
                "exp_bonus":            150,
        ]),
        ([      "quest":                "Ìú¿²",
                "quest_type":           "É±",
                "exp_bonus":            150,
        ]),
        ([      "quest":                "ÌúÁ¦",
                "quest_type":           "É±",
                "exp_bonus":            150,
        ]),
        ([      "quest":                "ÓæÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            150,
        ]),


//end 150k
});
 
//Find the First Index to have exp level >= x
int Find(int x)
{
        int total;
        int low,high,now;
        total=sizeof(quest);
        if(quest[0]["exp_bonus"]>=x)
                return 0;

        if(quest[total-1]["exp_bonus"]<x)
                return total-1; 
        low=0;
        high=total-1;
        now=(low+high)/2; 
        while(high-low>1) {
                if(quest[now]["exp_bonus"]>=x)
                        high=now;
                else 
                        low=now;
                now=(low+high)/2;
        }
        return high;
} 
mapping query_quest(int exp)
{
        int a,b,c; 
        int low,high;
        
        if(exp>1000) {
                low=exp-400; 
                high=exp+300;
        } else if (exp>730) {
                low=exp*8/10;
                high=exp*12/10;
        } else if (exp>600) {
                low=exp*8/10;
                high=exp*13/10;
        } else {
                low=exp*8/10;
                high=exp*14/10;
        } 
        if(low>5000) low=5000;   
        if(high<3) high=3; 
        a=Find(low);
        b=Find(high)-1;
        c=a+random(b+1-a);
        return quest[c];
} 

int TotalNumber()
{
        return sizeof(quest);
} 
int KillNumber()
{
        int count=0;
        int i,total;
        total=sizeof(quest);
        for(i=0;i<total;i++) {
                if (quest[i]["quest_type"]=="É±") count++;
        }
        return count;
}   
