#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Õ¼²·ÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1600,
        ]),
       ([      "quest":                 HIW"°×¾ÕË¿ÂÞÅÁ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1600,
        ]),
       ([      "quest":                 "ÍüÓÇ²Ý",
                "quest_type":           "Ñ°",
                "exp_bonus":            1600,
        ]),
       ([      "quest":                 "°×¹ûÊ÷Ò¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            1600,
        ]),
        ([      "quest":                HIG"ÂÌË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1600,
                "difficulty":           20,
        ]), 
        ([      "quest":                "ÄÚ¹¦ÐÄ·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1660,
        ]),
//end 1600
        ([      "quest":                "Ð¡Ä¾·¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            1500,
        ]),
        ([      "quest":                "Ò»¼ôÃ·»¨ÊÖÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1665,
        ]),
        ([      "quest":                "ÃÎÁ÷",
                "quest_type":           "É±",
                "exp_bonus":            1665,
       ]),
        ([      "quest":                "ÃÎÊ§",
                "quest_type":           "É±",
                "exp_bonus":            1665,
        ]),
//end 1665     
        ([      "quest":                "µûÁµ»¨½£·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1730,
        ]),
        ([      "quest":                "ÃÎ»Ã",
                "quest_type":           "É±",
                "exp_bonus":            1730,
        ]),
        ([      "quest":                "ÃÎÃÂ",
                "quest_type":           "É±",
                "exp_bonus":            1730,
        ]),
        ([      "quest":                HIW"±ùÊ¬"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1730,
        ]),
        ([      "quest":                "´óºÚÊ¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            1730,
        ]),
        ([      "quest":                "Ò»Òð",
                "quest_type":           "É±",
                "exp_bonus":            1730,
        ]),
//end 1730
        ([      "quest":                "Çï·ç²½·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
        ([      "quest":                "Çà´ÉÆ¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
      ([      "quest":                 HIR"Çé»¨"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
       ([      "quest":                 HIY"À°Ã·"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
       ([      "quest":                 CYN"ÎÞÃû»¨"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
       ([      "quest":                 "ÖñÍ²",
                "quest_type":           "Ñ°",
                "exp_bonus":            1800,
        ]),
//end 1800
        ([      "quest":                "ÆåµÀÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]),
        ([      "quest":                 HIW"°×¾ÕË¿ÂÞÅÁ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]),
       ([      "quest":                 "ÍüÓÇ²Ý",
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]),
       ([      "quest":                 "°×¹ûÊ÷Ò¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]),
        ([      "quest":                HIG"ÂÌË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]), 
        ([      "quest":                "ÄÚ¹¦ÐÄ·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1875,
        ]),
//end 1875
        ([      "quest":                "ÃÏÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            1950,
        ]),
        ([      "quest":                "ºÚ²¼ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1950,
        ]),
        ([      "quest":                "Ð¡Ä¾·¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            1950,
        ]),
        ([      "quest":                "Ò»¼ôÃ·»¨ÊÖÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            1950,
        ]),
        ([      "quest":                "ÃÎÁ÷",
                "quest_type":           "É±",
                "exp_bonus":            1950,
        ]),
        ([      "quest":                "ÃÎÊ§",
                "quest_type":           "É±",
                "exp_bonus":            1950,
        ]),
//end 1950
        ([      "quest":                "ºÚÅÛ¹«",
                "quest_type":           "É±",
                "exp_bonus":            2030,
                "difficulty":           15,
        ]),
        ([      "quest":                "°×¹û",
                "quest_type":           "Ñ°",
                "exp_bonus":            2030,
        ]),
        ([      "quest":                "ÃÎ¶ª",
                "quest_type":           "É±",
                "exp_bonus":            2030,
        ]),
        ([      "quest":                "ÃÎ¶¼",
                "quest_type":           "É±",
                "exp_bonus":            2030,
        ]),
        ([      "quest":                 "°×¹ûÊ÷Ò¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            2030,
        ]),
        ([      "quest":                HIG"ÂÌË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2030,
        ]), 
//end 2030
        ([      "quest":                "òùòðµºÎÄÑ§Æª",
                "quest_type":           "Ñ°",
                "exp_bonus":            2110,
        ]),
        ([      "quest":                "¶¾¸òó¡",
                "quest_type":           "É±",
                "exp_bonus":            2110,
        ]),
        ([      "quest":                HIY"Ð¡Ò°¾Õ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2110,
        ]),
       ([      "quest":                 HIY"À°Ã·"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2110,
        ]),
       ([      "quest":                 CYN"ÎÞÃû»¨"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2110,
        ]),
//end 2110
        ([      "quest":                "¾«¸ÖÔ°Í°",
                "quest_type":           "Ñ°",
                "exp_bonus":            2200,
                "difficulty":           15,
        ]),
        ([      "quest":                HIW"ÆÐÌá»¨"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2200,
        ]),
        ([      "quest":                "ÖñËñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            2200,
        ]),
        ([      "quest":                "ºÚÅÛ¹«",
                "quest_type":           "É±",
                "exp_bonus":            2200,
        ]),
//end 2200
        ([      "quest":                "ì¨Ê¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            2290,
        ]),        
        ([      "quest":                HIY"Ð¡Ò°¾Õ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2290,
        ]),
        ([      "quest":                 "°×¹ûÊ÷Ò¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            2290,
        ]),
        ([      "quest":                HIG"ÂÌË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2290,
        ]), 
//end 2290
        ([      "quest":                "Ð¡Í­½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2380,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ð¡Òø½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2380,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ð¡Ìú½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2380,
                "difficulty":           15,
        ]),
        ([      "quest":                "ç³Ò¹Ó£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2380,
        ]),
//end 2380
        ([      "quest":                "Ð¡Ìú½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2480,
                "difficulty":           15,
        ]),
        ([      "quest":                "Ã«Ò°",
                "quest_type":           "É±",
                "exp_bonus":            2480,
                 "difficulty":           15,
        ]),    
        ([      "quest":                "ì¨Ê¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            2480,
        ]),        
        ([      "quest":                HIY"Ð¡Ò°¾Õ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2480,
        ]),
//end 2480
        ([      "quest":                "òùòðµºÎÄÑ§Æª",
                "quest_type":           "Ñ°",
                "exp_bonus":            2580,
        ]),
        ([      "quest":               YEL"éÄÀÆ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2580,
                "difficulty":           15,
        ]),
        ([      "quest":                "ºìÄ¾´ó¹ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            2580,
                "difficulty":           15,
        ]),
        ([      "quest":                "Óü×ä³¤",
                "quest_type":           "É±",
                "exp_bonus":            2580,
                "difficulty":           20,
        ]),
        ([      "quest":                "Ð¡Ìú½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2380,
                "difficulty":           15,
        ]),
//end 2580
        ([      "quest":                RED"Õ¶Âíµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2680,
                "difficulty":           15,
        ]),
        ([      "quest":                HIG"Í­½£"NOR,
                "quest_type":           "É±",
                "exp_bonus":            2680,
                "difficulty":           10,
        ]),
        ([      "quest":                HIW"Òø½£"NOR,
                "quest_type":           "É±",
                "exp_bonus":            2680,
                "difficulty":           10,
        ]),
        ([      "quest":               YEL"éÄÀÆ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2680,
                "difficulty":           15,
        ]),
//end 2680
        ([      "quest":                HIR"Ìú½£"NOR,
                "quest_type":           "É±",
                "exp_bonus":            2790,
                "difficulty":           15,
        ]),
        ([      "quest":                "Ð¡½ð½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            2790,
        ]),
        ([      "quest":                HIR"ºìË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2790,
                "difficulty":           20,
        ]),       
        ([      "quest":                WHT"ÆÆ¾É²¼Ñ¥"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            2790,
        ]),
//end 2900
        ([      "quest":                HIC"ÇàÉÀ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3010,
        ]),
        ([      "quest":                HIG"´ó·çµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3010,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ð¡Ä¾·¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            3010,
        ]),
        ([      "quest":                "Ò»¼ôÃ·»¨ÊÖÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3010,
        ]),
        ([      "quest":                "ÃÎÁ÷",
                "quest_type":           "É±",
                "exp_bonus":            3010,
        ]),
        ([      "quest":                "ÃÎÊ§",
                "quest_type":           "É±",
                "exp_bonus":            3010,
        ]),
//end 3010
        ([      "quest":                "ÐùÔ¯ÈýÈ±",
                "quest_type":           "É±",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),
        ([      "quest":                "¹ÅÄ¾ÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
        ]),
/*        ([      "quest":                "Ö½µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),*/
        ([      "quest":                "ÖÐÔ­Ò»µã"HIR"ºì"NOR,
                "quest_type":           "É±",
                "exp_bonus":            3120,
        ]),    
        ([      "quest":                HIR"Ñª½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
        ]),
        ([      "quest":                "ÖìÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            3120,
        ]),
        ([      "quest":                 "ÖÐÄêºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),
        ([      "quest":                "Çà²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
        ]),
        ([      "quest":                "Ì´Ä¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),   
        ([      "quest":                "¹Ø¶«ºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),
        ([      "quest":                HIR"¿ªÌÅÆÆ¶ÇµÄ²ÐÈ±Ê¬Ìå"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
                "difficulty":           20,
        ]),  
        ([      "quest":                HIR"ÏÊÑªÁÜÀìµÄÈËÍÈ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
                "difficulty":           10,
        ]),     
        ([      "quest":                RED"ÈËÈâ°ü"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
                "difficulty":           10,
        ]),  
        ([      "quest":                 "ÖÖ»¨µÄÀÏºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            3120,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÎÚÇÊ³¤µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
        ]),
        ([      "quest":                YEL"Ä¾åì"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3120,
        ]),
//end 3120
       ([      "quest":                "Ìì·ãÊ®ËÄÀÉ",
                "quest_type":           "É±",
                "exp_bonus":            3250,
        ]),
        ([      "quest":                "ÎÚÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
        ]), 
        ([      "quest":                 "É¨µØµÄÀÏºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           20,
        ]),
        ([      "quest":                 "Ð¡Îä",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           35,
        ]),
        ([      "quest":                 "Ã«Õ½",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           25,
        ]),
        ([      "quest":                CYN"Çå·ç½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                 "difficulty":           20,
        ]),
        ([      "quest":                HIM"×ÏË®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                "difficulty":           25,
        ]),
        ([      "quest":                "È¸ôáÓñºÐ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                "difficulty":           15,
        ]),
        ([      "quest":                HIB"±ÌÑªº£ÌÄ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                "difficulty":           10,
        ]),
        ([      "quest":                "Ò»Ëã",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           15,
        ]),
        ([      "quest":                 "Ò»Óà",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),
        ([      "quest":                 "Ò»Ê±",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),     
        ([      "quest":                 "Ò»¸ñ",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),
       ([      "quest":                HIB"À¶Ë®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                "difficulty":           20,
        ]), 
        ([      "quest":                WHT"Ìì²ÐÉÀ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),
        ([      "quest":                WHT"Ìì·ÏÉÀ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),
        ([      "quest":                "ÍêÑÕ¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           15,
        ]),
        ([      "quest":                "ÍêÑÕÌú",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           15,
        ]),
        ([      "quest":                "Ò»Ëã",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                "difficulty":           15,
        ]),
        ([      "quest":                 "Ò»Óà",
                "quest_type":           "É±",
                "exp_bonus":            3250,
                 "difficulty":           15,
        ]),
       ([      "quest":                HIB"À¶Ë®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3250,
                "difficulty":           20,
        ]), 
// end 3250        
       ([      "quest":                HIY"¾ÅÁúÏ·Öé±Þ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3390,
        ]),
        ([      "quest":                 "½¹»¯",
                "quest_type":           "É±",
                "exp_bonus":            3390,
                "difficulty":           20,
        ]),
        ([      "quest":                 "½¹ÀÍ",
                "quest_type":           "É±",
                "exp_bonus":            3390,
                "difficulty":           20,
        ]),
        ([      "quest":                 "Ò»ÒÑ",
                "quest_type":           "É±",
                "exp_bonus":            3390,
        ]),
        ([      "quest":                 "Ò»µÄ",
                "quest_type":           "É±",
                "exp_bonus":            3390,
        ]),
        ([      "quest":                 "Ò»Âä",
                "quest_type":           "É±",
                "exp_bonus":            3390,
        ]),
        ([      "quest":                 "ÍÁÀÎÓü×ä",
                "quest_type":           "É±",
                "exp_bonus":            3390,
                "difficulty":           25,
        ]),
        ([      "quest":                "ÔÆÃ÷",
                "quest_type":           "É±",
                "exp_bonus":            3390,
        ]),
        ([      "quest":                "ÃÉÃæ½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            3390,
        ]),
       ([      "quest":                HIB"À¶Ë®¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3390,
                "difficulty":           20,
        ]), 
//end 3390
        ([      "quest":                "¾Å»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3540,
                "difficulty":          15,
        ]),        

        ([      "quest":                "¸ðÂ×",
                "quest_type":           "É±",
                "exp_bonus":            3540,
                 "difficulty":          20,
        ]), 
        ([      "quest":                "ÍõÕðÏæ",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),  
        ([      "quest":                 "Ò»ÄÇ",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                 "Ò»Ëù",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                "ÑÔÐ¡Ð¡",
                "quest_type":           "É±",
                "exp_bonus":            3540,
                 "difficulty":          20,
        ]),
        ([      "quest":                 "Ë«Ë«",
                "quest_type":           "É±",
                "exp_bonus":            3540,
                "difficulty":           25,
        ]),
        ([      "quest":                 "ÀîºìÓ£",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                "ºìÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                "Æß´ç³¤µÄ¶Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            3540,
                "difficulty":           35,

        ]),
        ([      "quest":                "´Ö²¼°×ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                "ÑîÂÌÁø",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),
        ([      "quest":                 "°×ÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            3540,
                 "difficulty":           15,
        ]),
        ([      "quest":                HIG"ÂþÌì½£Æø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3540,
        ]),       
        ([      "quest":                "ÎâÇà",
                "quest_type":           "É±",
                "exp_bonus":            3540,
        ]),
//end 3540
        ([      "quest":                HIR"Îå"NOR+HIY"É«"+HIG"Ë®"+HIM"¾§"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3700,
                "difficulty":           55,
        ]), 
//end 3700
        ([      "quest":                "ÀîÝà»ª",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           20,
        ]), 
        ([      "quest":                "¹ù´óÂ·",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           20,
        ]),

        ([      "quest":                "°×Èý¿Õ",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           20,
        ]),
        ([      "quest":                HIR"µÎÑªµÄºìÃµ¹å"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3890,
                "difficulty":           20,
        ]), 
        ([      "quest":                HIC"ÒøÇ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3890,
                "difficulty":           25,
        ]), 
        ([      "quest":               "²¼ÍÞÍÞ",
                "quest_type":           "Ñ°",
                "exp_bonus":            3890,
                "difficulty":           25,
        ]), 
        ([      "quest":                "¿àâÖÉÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           15,
        ]),
        ([      "quest":                 "À÷ðÊ",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           25,
        ]),
        ([      "quest":                "¸ßÁ¦",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                 "difficulty":           40,
        ]),
        ([      "quest":                 "Î÷ÃÅÓñ",
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           30,

        ]),
        ([      "quest":              HIW"°×Òø¼×"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            3890,
                "difficulty":           10,
        ]), 
        ([      "quest":                HIC"Òø¼×ÎäÊ¿"NOR,
                "quest_type":           "É±",
                "exp_bonus":            3890,
                "difficulty":           20,
        ]),
//end 3890
        ([      "quest":                HIG"ÇàÖñÕÈ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
                "difficulty":           10,
        ]), 
        ([      "quest":                "Ð»³¤Çä",
                "quest_type":           "É±",
                "exp_bonus":            4040,
                "difficulty":           20,
        ]),
        ([      "quest":                "åÐÒ£ºî",
                "quest_type":           "É±",
                "exp_bonus":            4040,
        ]), 
       ([      "quest":                "½ð²®Ê¤ÒÄ",
                "quest_type":           "É±",
                "exp_bonus":            4040,
                "difficulty":           20,
        ]),
        ([      "quest":                RED"ÉîºìÉ®ÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
        ]), 
        ([      "quest":                YEL"»ÆÉ«·ðÖé"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
        ]), 

        ([      "quest":                "Íõ¶¯",
                "quest_type":           "É±",
                "exp_bonus":            4040,
        ]),
        ([      "quest":                "ÆÆ¾ÉÒÂ·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
        ]), 
        ([      "quest":                HIC"ÁÁÒøÇ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
        ]), 
        ([      "quest":                "ÀÏºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            4040,
                "difficulty":           30,
        ]),
        ([      "quest":                "Ï´µÃ·¢°×µÄÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
                "difficulty":           20,
        ]),
        ([      "quest":                "Çà²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4040,
                "difficulty":           20,
        ]),
        ([      "quest":                "µË¶¨ºò",
                "quest_type":           "É±",
                "exp_bonus":            4040,
        ]),
        ([      "quest":                "ÈÎ´È",
                "quest_type":           "É±",
                "exp_bonus":            4040,
                "difficulty":           20,
        ]),
//end 4040
        ([      "quest":                 "¸µºìÑ©",
                "quest_type":           "É±",

                "exp_bonus":            4190,
                "difficulty":           20,
        ]),
        ([      "quest":                "°ÔÍõÇ¹Æ×",
                "quest_type":           "Ñ°",
                "exp_bonus":            4190,
        ]),
        ([      "quest":                "¶¡Ï²",
                "quest_type":           "É±",
                "exp_bonus":            4190,
                "difficulty":           20,
        ]),
        ([      "quest":                "¹é¶«¾°",
                "quest_type":           "É±",
                "exp_bonus":            4190,
        ]),
        ([      "quest":                "ÍõÈôÀ¼",
                "quest_type":           "É±",
                "exp_bonus":            4190,
                "difficulty":           25,
        ]), 
        ([      "quest":                "°ËÔÂ³õ°Ë",
                "quest_type":           "É±",
                "exp_bonus":            4190,
                "difficulty":           35,
        ]), 
        ([      "quest":                RED"ÍÀµ¶"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4190,
        ]),  
        ([      "quest":                HIR"½ðÇ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4190,
                "difficulty":           20,
        ]),  
        ([      "quest":              RED"ºìÉ«·ðÖé"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4190,
                "difficulty":           20,

        ]), 
        ([      "quest":               WHT"°×É«·ðÖé"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4190,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÐÄµÆ",
                "quest_type":           "É±",
                "exp_bonus":            4190,
                "difficulty":           20,
         ]),
        ([      "quest":                "ÐÄÖò",
                "quest_type":           "É±",
                "exp_bonus":            4190,
                "difficulty":           20,
        ]),
// end 4190
        ([      "quest":              HIY"»Æ½ð¼×"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
                "difficulty":           20,
        ]), 
        ([      "quest":               HIY"½ðêª"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
                "difficulty":           20,
        ]),
        ([      "quest":                "¶«º£°×ÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            4300,
        ]),
        ([      "quest":              HIW"Ó£»¨ÎäÊ¿·þ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
        ]), 
        ([      "quest":               "ÎäÊ¿µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
        ]),

        ([      "quest":                "²®ÂÞ¸÷´ð",
                "quest_type":           "É±",
                "exp_bonus":            4300,
        ]), 
        ([      "quest":                "ÐÄÃ¼",
                "quest_type":           "É±",
                "exp_bonus":            4300,
                "difficulty":           20,
        ]),
        ([      "quest":                "ÐÄÊ÷",
                "quest_type":           "É±",
                "exp_bonus":            4300,
                "difficulty":           20,
        ]),
        ([      "quest":                "Ð¡É³ÃÖ",
                "quest_type":           "É±",
                "exp_bonus":            4300,
        ]),
        ([      "quest":                "Á«ÈØ",
                "quest_type":           "É±",
                "exp_bonus":            4300,
        ]),
        ([      "quest":               HIY"³ÈË¿ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
        ]), 
        ([      "quest":                "ÂéÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4300,
        ]),  
 // end 4300  
        ([      "quest":                 BLU"À¶ÒÂ¹¬Å®"NOR,
                "quest_type":           "É±",
                "exp_bonus":            4420,
        ]),
         ([      "quest":                "Á«·ç¶ù",
                "quest_type":           "É±",
                "exp_bonus":            4420,
        ]),

        ([      "quest":                "Ð»ÕÆ¹ñ",
                "quest_type":           "É±",
                "exp_bonus":            4420,
        ]),
        ([      "quest":                "ÖìÔå",
                "quest_type":           "É±",
                "exp_bonus":            4420,
        ]),
        ([      "quest":                RED"ºìË¿ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4420,
        ]),
        ([      "quest":               BLU"À¶Ë¿ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4420,
        ]),  
        ([      "quest":                "ÅÌµÆæÚ¶û",
                "quest_type":           "É±",
                "exp_bonus":            4420,
         ]),
        ([      "quest":                "ÔÆ¿Õ",
                "quest_type":           "É±",
                "exp_bonus":            4420,
         ]),
        ([      "quest":                "ÕÔ¸Õ",
                "quest_type":           "É±",
                "exp_bonus":            4420,
        ]),  
 // end 4420
        ([      "quest":                "Ìì·å",
                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]), 
        ([      "quest":                 HIR"ºìÁ«»¨"NOR,
                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]),
        ([      "quest":                "³àÑôµÀ³¤",
                "quest_type":           "É±",

                "exp_bonus":            4460,
        ]),
        ([      "quest":                "ÍõÓêÂ¥",
                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]),
        ([      "quest":                HIY"ÑÌÓêäìäì»·½ðÅÛ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]), 
        ([      "quest":                HIY"½ð¼×ÎäÊ¿"NOR,
                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]),
        ([      "quest":                "Î§Æå×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]), 
        ([      "quest":                "Ò»³¾²»È¾µÄ°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]),  
        ([      "quest":                "ÆÆ¾É²»¿°µÄÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]),
        ([      "quest":                "Ë¿Ö¯µÄµÀ·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]), 
        ([      "quest":                "ÀÇÍÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4460,
        ]),  
        ([      "quest":                HIY"³ÈÒÂ¹¬Å®"NOR,
                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]),
        ([      "quest":                RED"ºìÒÂ¹¬Å®"NOR,

                "quest_type":           "É±",
                "exp_bonus":            4460,
        ]),
//end 4540
        ([      "quest":                "ÎÞºÞÉú",
                "quest_type":           "É±",
                "exp_bonus":            4650,
         ]),
        ([      "quest":                "Æ½·²ÉÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            4650,
         ]),
        ([      "quest":                "»Û´óÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            4650,
         ]),
        ([      "quest":                "Ë¿ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]), 
        ([      "quest":                "Ò¹µÛ",
                "quest_type":           "É±",
                "exp_bonus":            4650,
                "difficulty":           10,
         ]),
        ([      "quest":                "±ªÆ¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]), 
        ([      "quest":                WHT"ÈËÐÎ¹ÖÎï"NOR,
                "quest_type":           "É±",
                "exp_bonus":            4650,
                "difficulty":           10,
         ]),
        ([      "quest":                "ÖñóÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]),  
        ([      "quest":                "»ÒÅÛ",

                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]), 
        ([      "quest":                "ÀÏµ¶°Ñ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            4650,
                "difficulty":           20,
         ]),
        ([      "quest":                "ºÚÉ«µÄË¿ÖÊ³¤È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]), 
        ([      "quest":                "ÀÏ¸¾ÈË",
                "quest_type":           "É±",
                "exp_bonus":            4650,
                "difficulty":           20,
         ]),
        ([      "quest":                BLU"À¶Ë¿ïí"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]),  
        ([      "quest":                HIY"³ÈË¿´ø"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]), 
        ([      "quest":                RED"ºìË¿Ã±"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4650,
        ]),  
//end 4650
        ([      "quest":                "Ç®²»×¬",
                "quest_type":           "É±",
                "exp_bonus":            4840,
        ]),
        ([      "quest":                "Ç®²»Òª",
                "quest_type":           "É±",
                "exp_bonus":            4840,
         ]),
        ([      "quest":                "ÇàÄ¾½£",

                "quest_type":           "Ñ°",
                "exp_bonus":            4840,
        ]), 
        ([      "quest":                "ÒóÏÛ",
                "quest_type":           "É±",
                "exp_bonus":            4840,
                "difficulty":           20,
         ]),
        ([      "quest":                "×³ÄêºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            4840,
                "difficulty":           20,
         ]),
        ([      "quest":                "ºÚ²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4840,
        ]), 
        ([      "quest":                "ÈÕºó",
                "quest_type":           "É±",
                "exp_bonus":            4840,
        ]),
        ([      "quest":                "ÌúÖÐÌÄ",
                "quest_type":           "É±",
                "exp_bonus":            4840,
         ]),
        ([      "quest":                "ÌìÇàË¿ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4840,
        ]), 
//end 4840
        ([      "quest":                HIG"Óµ´äÈ¹"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4990,
        ]), 
        ([      "quest":                "ÀÏÉ®",
                "quest_type":           "É±",
                "exp_bonus":            4990,
                "difficulty":           20,
         ]),

        ([      "quest":                "»Ò²¼ÉÙÁÖÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            4990,
                "difficulty":           20,
        ]), 
        ([      "quest":                "Ð»Ïþ·å",
                "quest_type":           "É±",
                "exp_bonus":            4990,
                "difficulty":           20,
         ]),
        ([      "quest":                "ÈýÉÙÒ¯µÄ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            4990,
        ]), 
        ([      "quest":                "ÉÏ¹Ù½ðºç",
                "quest_type":           "É±",
                "exp_bonus":            4990,
                "difficulty":           20,
         ]),
        ([      "quest":                "Ò¶¹Â³Ç",
                "quest_type":           "É±",
                "exp_bonus":            4990,
                "difficulty":           20,
         ]),
        ([      "quest":                CYN"Ä«×Ó½£"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            4990,
                "difficulty":           20,
         ]),
        ([      "quest":                "Áú·ïË«»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            4990,
        ]), 
// end 4990
});
 
//Find the First Index to have exp level >= x
int Find(int x)
{
        int total;
        int low,high,now;
        total=sizeof(quest); 
        if(quest[0]["exp_bonus"]>=x)
                return 0;
        if(quest[total-1]["exp_bonus"]<x)
                return total-1; 
        low=0;
        high=total-1;
        now=(low+high)/2; 

        while(high-low>1) {
                if(quest[now]["exp_bonus"]>=x)
                        high=now;
                else 
                        low=now;
                now=(low+high)/2;
        }
        return high;
} 
mapping query_quest(int exp)
{
        int a,b,c; 
        int low,high; 
        if(exp>1000) {
                low=exp-400; 
                high=exp+300;
        } else if (exp>830) {
                low=exp*7/10;
                high=exp*12/10;
        } else if (exp>600) {
                low=exp*8/10;
                high=exp*13/10;
        } else {
                low=exp*8/10;
                high=exp*14/10;
        } 
        if(low>5000) low=5000;   
        if(high<3) high=3; 
        a=Find(low);
        b=Find(high)-1;
        c=a+random(b+1-a);
        return quest[c];
} 
int TotalNumber()
{
        return sizeof(quest);
} 
int KillNumber()
{

        int count=0;
        int i,total;
        total=sizeof(quest);
        for(i=0;i<total;i++) {
                if (quest[i]["quest_type"]=="É±") count++;
        }
        return count;
} 
