#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏ°åÄï",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÕÅÌú½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÁúÐ¡ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÓÍÀ±ÖíÅÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ö½Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Óæ·ò",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¤ÐÄ¾µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ò°Ñ¼",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "À×»ðÖé",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å©¾ßµêÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´©¿ªñÉ¿ãµÄÐ¡º¢¶ù",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿ªñÉ¿ã",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Çå²¨¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÆÆ¾É²»¿°µÄ³¤ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ô¬¼§",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "°×³ñ³¤Åû·ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÍõÊ¯½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÑîÀÏÌ«",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å©¼ÒÅ®",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¼¦Ã«ë¦×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂôÓãµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÏÊÓã",
                "quest_type":           "Ñ°",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "Ð¡µ£··",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ð¡··",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂíÀÏËÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å£Æ¤´ü",
                "quest_type":           "Ñ°",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂòÂòÌá",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Î¬Îá¶û»¨Ã±",
                "quest_type":           "Ñ°",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "ÎÞºË°×ÆÏÌÑ",
                "quest_type":           "Ñ°",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "°¢ÒÀ¹ÅÀö",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "°¬ÌáÀ­Ë¹È¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}       
