#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ïº",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Óã",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "´óÇà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Çà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Çà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Âí××Ä¾Ë¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×É«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºÚÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÌôË®µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¿³²ñµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "»Ò²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°×²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "·ç¾²",
                "quest_type":           "É±",
                "exp_bonus":            40,
                "time":                 840,
        ]),
        ([      "quest":                "ÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÌ¶·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌôÉ½·ò",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ÖÄ¾±âµ£",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "âã»ÚÍ½",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÅ·¼",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂãÌåÅ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "É¥¾¡ÌìÁ¼µÄÐóÉú",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡¶µ¶µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Î÷ÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²É»¨æ¤",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "±Ú»¢",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡Ã¨ßä",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Íõ»¢",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Áø·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ïã¿Í",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÃÎ»À",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ñà¶ù",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²Ý±àÂìòÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡±¦¶ù",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Öñ·òÈË",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸´ºÇï¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸´¸·¨ÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¡¸¹÷ÊõÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Æ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "µ¥µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}       
