#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Ð¡¾ê",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÆÆÀÃµÄ·Ûºì²¼ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "öÇÓãºâ±ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÏìÎ²Éß",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Óü×ä",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¶Û½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»¤Ôº",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ð¡¶Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¹Ø¶«´óºº",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ñª³¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Åí³¤¾»",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÎäÁÖÐ¡ºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ãçµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ó­¿ÍÉ®",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÔÆÓÎÉ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "´Ö²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÃÞ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ºÚ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "°×²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "´Ö²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÃÞ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ºÚ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "°×²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¼«ÀÖåÐÒ£É¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»¯Ê¬·Û",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ò¹ÐÐÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¾«¸Ö·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ºì×ìÐ¡ÂéÈ¸",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÀÏÎÝÈË",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "öùÓã",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ë®Éß",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "½ðË¿È¸",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¿Õ¹â",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "·¹²§",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÁøÈôËÉ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´óÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¹Â»ê",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Õ½»ê",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÍÂÂ³·¬ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÎÚÀ­²´ÉÌÈË",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "òÐòÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÂìÒÏ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ó¢¼ªÉ³Ð¡µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "âÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÈËÓ°",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "·çÉ§ÑÅÈË",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÐíÁ®Áú",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "³¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Çà·æ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}        
