#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ºÚ¹·",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Í­Ç®ïÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "»¨¹Ñ¸¾",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            55,
        ]),
        ([      "quest":                "»¤ËÂÀ®Âï",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "³ÇÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "´óºìÉ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Èý»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ËþÉ®",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¶«·ç",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÄÏ·ç",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Î÷·ç",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "±±·ç",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ºìÖÐ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Òø»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ºÚÉ«½Ì·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÍõÈô¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÕÅËÆ¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÀîÈü¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÕÔÈç¸Ö",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "»ÆÉ«½Ì·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "¿¼Éú",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "·çÔÆÂí¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "·®·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀËÓÎÊ«ÈË",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ñ©ÌãëÙÖ¬Âí",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Å£Æ¤Âí°°",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Â½Îå´¨",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ºÚÉ«×¯·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "·çóÝ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÎÄÈËÄ«¿Í",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "»ÆÒÂÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "½ðÇ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "µ¥ÉíÌË×ÓÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "»õÆ±",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "·çÁè",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ºÚ¹Ú¾Þòþ",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ÊÝæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÅÖæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "·çÉ§ÑÅÈË",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}    
