#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "À¶ÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÆßÐÇ´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÂÌ¶¹Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Íã¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Çà¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¾Â²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "´ó°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "´óÇà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡Çà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×ÓñÐ¡ÂíÍ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Âí××Ä¾Ë¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÃÛ·ä",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»Æ½ð",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ËòÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "µÇÍ½×Ó",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÅÙ»¨ÓÍ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¼¦Èâ°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºìÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÂÌÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»ÆÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×É«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºÚÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "³¯°ÝµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "É¨µØµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÉÕ·¹µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÌôË®µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¿³²ñµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÌÔÃ×µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´òÔÓµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Äî¾­µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "»Ò²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°×²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "·ç¾²",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ë®ÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»¨½³",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÕÔ¹úÌ©",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ô°¹¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÌ¶·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "³ÁÏãÕòµÄµØÍ·Éß",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌôÉ½·ò",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ÖÄ¾±âµ£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "âã»ÚÍ½",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÅ·¼",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂãÌåÅ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÄêÇàÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "É¥¾¡ÌìÁ¼µÄÐóÉú",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "²ÊÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡¶µ¶µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Î÷ÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å®Ó¶ÈË",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÇàÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Áù½Ç´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¼¦Ã«",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "²É»¨æ¤",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×ÏÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "°ËÀãÐþÌú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´ó±è×Ó¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "µÇÉ½Õß",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "²ÉÁâÅ®",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "±Ú»¢",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡Ã¨ßä",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Íõ»¢",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Áø·òÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ïã¿Í",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÃÎ»À",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ð¡µ£··",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñà¶ù",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²Ý±àÂìòÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡±¦¶ù",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Öñ·òÈË",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "À¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}        
