#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "´¾ÓÚ»³Ì«",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÉßÁÛÆ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Ò¶Áé",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Ò¶Ñ©",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            60,
        ]),
        ([      "quest":                "¹·ÀÉ¾ý",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            60,
        ]),
        ([      "quest":                "»ÆÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Ð¡À¼",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "¶¾ÁúÉ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Äµµ¤",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "¶¬Çà",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Ãµ¹å",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "¶Å¾é",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "°×ÅÛ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Àî³¤É÷",
                "quest_type":           "É±",
                "time":                 840,
                "exp_bonus":            60,
        ]),
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¹©Ïã",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Ì«¼«È­Á·¹¦Í¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÂäµÚÊéÉú",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "×¥ÆÆÃÀÈËÁ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "°×¾±»ÒÐÜ",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Îý»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "²éÃÍ",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "·¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":               HIY"Îå" + HIR"²Ê"NOR + "½ôÉíÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀÏÊµºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "¿ñæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÍÅ½ð¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "´óºú×ÓºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀîÉñÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "ÀÏÉ½Ñò",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                "Öî¸ðÀ×",
                "quest_type":           "É±",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Ð¡Í¯",
                "quest_type":           "É±",
                "exp_bonus":            50,
        ]),
        ([      "quest":               HIY"Ç³»ÆÐ¡¹Ó"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "Òõ±ö",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                HIR"ÇáºìÂÞç­ÒÂ"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "±öÅ«",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                HIR"ÇáºìÂÞç­É´"NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "ËÎÖÐ",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}      
