#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                " ’∆∆¿√µƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "«Æ",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "È‘∑Ú",
                "quest_type":           "…±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ã˙∏´",
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "∆Úÿ§",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿œ∆Úÿ§",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]), 
        ([      "quest":                "æ… È",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "œ∫",
                "quest_type":           "…±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "”„",
                "quest_type":           "…±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "øæ”„»‚",
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ª§–ƒæµ",
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIC"Œﬁ”∞…Ò’Î"NOR,
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "“∞—º",
                "quest_type":           "…±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿◊ª÷È",
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "”Ò∑¢Ù¢",
                "quest_type":           "—∞",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "÷Òµ∂",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "÷ÒΩ£",
                "quest_type":           "—∞",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»˝«Âµ¿ ı",
                "quest_type":           "—∞",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "°∏±ﬁ ı»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏µ∂ ı»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏Ω£ ı»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏≤’–√ÿæˆ°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏…¡∂„÷Æ ı°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏»≠∑®»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏¥∏∑®»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°∏π˜ ı»Î√≈°π",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "∆§±ﬁ",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ƒæπ˜",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "µ•µ∂",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ã˙¥∏",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Õ’±≥¿œ»À",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ƒ•≤Àµ∂µƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¥©ø™Ò…ø„µƒ–°∫¢∂˘",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬Ù”„µƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬Ú”„µƒ–°π√ƒÔ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "≈©º“≈Æ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "º¶√´Î¶◊”",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "≈©∑Ú",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "≈©æﬂµÍ¿œ∞Â",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "∞¢∑¢",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "∫˙”¢",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿œ≤√∑Ï",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Õ¡ÊΩ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬Ù≤Àµƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¥Û≈÷◊”",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬ÙÕÊæﬂµƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬Ù“©µƒ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Õı» µ¬",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "µÍ–°∂˛",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿œ∞ÂƒÔ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "’≈Ã˙Ω≥",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "…œ¡ÀƒÍºÕµƒ¿œÃ´∆≈",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "≤Ë≤© ø",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡˙–°‘∆",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "”Õ¿±÷Ì≈≈",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "”„œ„»‚Àø",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "÷Ωª®",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "÷Ω«Æ",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "÷ÌÕ∑",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ω∑—Œ≈≈π«",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "«ßΩ–°Ω„",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "“¯Ù¢",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "«·¬ﬁ≥Ò…¿",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¬Ú¬ÚÃ·",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Œ¨Œ·∂˚ª®√±",
                "quest_type":           "—∞",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "Œﬁ∫À∞◊∆œÃ—",
                "quest_type":           "—∞",
                 "exp_bonus":            10,
        ]),
        ([      "quest":                "∞¢“¿π≈¿ˆ",
                "quest_type":           "…±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "∞¨Ã·¿≠Àπ»π",
                "quest_type":           "—∞",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Õ¡∑À",
                "quest_type":           "…±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "∆§“¬",
                "quest_type":           "—∞",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "π¬ªÍ“∞πÌ",
                "quest_type":           "…±",
                "exp_bonus":            15,
        ]), 
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}      
